# Generated by Django 5.2.17 on 2026-09-25 05:24

import common.crypto
import common.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretHolder',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secret', common.crypto.EncryptedTextField(blank=True, default='')),
                ('optional_secret', common.crypto.EncryptedTextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
