# Generated by Django 5.2.17 on 2026-09-26 08:56

import common.fields
import common.ids
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from apps.inventory.defaults import DEFAULT_WAREHOUSE_CODE, DEFAULT_WAREHOUSE_NAME
from common.db_ops import EnableRLS, MakeAppendOnly

# A posted goods receipt never changes, except that cost-pending lines gain their cost once
# ("complete costs", ADR-041). Draft receipts and their lines are freely editable.
INWARD_GUARD_SQL = """
CREATE FUNCTION inventory_inward_guard() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.status = 'POSTED' THEN
            RAISE EXCEPTION 'posted goods receipt % cannot be deleted', OLD.number
            USING ERRCODE = 'restrict_violation';
        END IF;
        RETURN OLD;
    END IF;
    IF OLD.status = 'POSTED' AND
       (to_jsonb(NEW) - 'total_cost' - 'cost_pending_lines' - 'updated_at')
       IS DISTINCT FROM (to_jsonb(OLD) - 'total_cost' - 'cost_pending_lines' - 'updated_at') THEN
        RAISE EXCEPTION 'posted goods receipt % cannot be changed', OLD.number
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END $$ LANGUAGE plpgsql;
CREATE TRIGGER inward_guard BEFORE UPDATE OR DELETE ON inventory_stockinward
    FOR EACH ROW EXECUTE FUNCTION inventory_inward_guard();

CREATE FUNCTION inventory_inward_line_guard() RETURNS trigger AS $$
DECLARE
    parent_status text;
    cost_cols text[] := ARRAY['unit_cost', 'line_cost', 'cost_status', 'cost_completed_at',
                              'cost_completed_by_id', 'updated_at'];
BEGIN
    SELECT status INTO parent_status FROM inventory_stockinward
        WHERE id = COALESCE(NEW.inward_id, OLD.inward_id);
    IF parent_status IS DISTINCT FROM 'POSTED' THEN
        RETURN COALESCE(NEW, OLD);
    END IF;
    IF TG_OP = 'UPDATE' AND OLD.cost_status = 'PENDING' AND NEW.cost_status = 'SET'
       AND (to_jsonb(NEW) - cost_cols) = (to_jsonb(OLD) - cost_cols) THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'lines of a posted goods receipt cannot be changed (%)', TG_OP
            USING ERRCODE = 'restrict_violation';
END $$ LANGUAGE plpgsql;
CREATE TRIGGER inward_line_guard BEFORE INSERT OR UPDATE OR DELETE ON inventory_stockinwardline
    FOR EACH ROW EXECUTE FUNCTION inventory_inward_line_guard();
"""

INWARD_GUARD_SQL_REVERSE = """
DROP TRIGGER IF EXISTS inward_line_guard ON inventory_stockinwardline;
DROP FUNCTION IF EXISTS inventory_inward_line_guard();
DROP TRIGGER IF EXISTS inward_guard ON inventory_stockinward;
DROP FUNCTION IF EXISTS inventory_inward_guard();
"""


def backfill_warehouses_and_levels(apps, schema_editor):
    """Every existing tenant gets its default warehouse, and every product a zero stock level."""
    Tenant = apps.get_model("platform", "Tenant")
    Product = apps.get_model("catalog", "Product")
    Warehouse = apps.get_model("inventory", "Warehouse")
    StockLevel = apps.get_model("inventory", "StockLevel")
    for tenant_id in Tenant.objects.values_list("id", flat=True):
        warehouse = Warehouse.objects.filter(tenant_id=tenant_id, is_default=True).first()
        if warehouse is None:
            warehouse = Warehouse.objects.create(
                tenant_id=tenant_id,
                code=DEFAULT_WAREHOUSE_CODE,
                name=DEFAULT_WAREHOUSE_NAME,
                is_default=True,
            )
        StockLevel.objects.bulk_create(
            [
                StockLevel(tenant_id=tenant_id, product_id=product_id, warehouse=warehouse)
                for product_id in Product.objects.filter(tenant_id=tenant_id).values_list(
                    "id", flat=True
                )
            ],
            ignore_conflicts=True,
            batch_size=1000,
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_own_brand_cost_price'),
        ('platform', '0005_settings_overrides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('address_line1', models.CharField(blank=True, default='', max_length=200)),
                ('address_line2', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('pincode', models.CharField(blank=True, default='', max_length=6)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.state')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('INWARD', 'Goods received'), ('SALE', 'Dispatched'), ('RETURN', 'Returned'), ('ADJUSTMENT_IN', 'Adjustment in'), ('ADJUSTMENT_OUT', 'Adjustment out'), ('DAMAGE', 'Damaged'), ('TRANSFER_IN', 'Transfer in'), ('TRANSFER_OUT', 'Transfer out'), ('RESERVE', 'Reserved for an order'), ('RELEASE', 'Reservation released')], max_length=30)),
                ('quantity', common.fields.QtyField(decimal_places=3, max_digits=14)),
                ('delta_on_hand', common.fields.QtyField(decimal_places=3, max_digits=14)),
                ('delta_reserved', common.fields.QtyField(decimal_places=3, max_digits=14)),
                ('on_hand_after', common.fields.QtyField(decimal_places=3, max_digits=14)),
                ('reserved_after', common.fields.QtyField(decimal_places=3, max_digits=14)),
                ('unit_cost', common.fields.UnitCostField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('value', common.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('reference_type', models.CharField(choices=[('INWARD', 'Goods receipt'), ('ADJUSTMENT', 'Adjustment'), ('ORDER', 'Order'), ('ORDER_LINE', 'Order line'), ('FULFILMENT', 'Shipment'), ('CREDIT_NOTE', 'Credit note'), ('ALLOCATION', 'Backorder allocation')], max_length=30)),
                ('reference_id', models.UUIDField()),
                ('reference_number', models.CharField(blank=True, default='', max_length=40)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_on_hand', common.fields.QtyField(decimal_places=3, default=0, max_digits=14)),
                ('quantity_reserved', common.fields.QtyField(decimal_places=3, default=0, max_digits=14)),
                ('quantity_backordered', common.fields.QtyField(decimal_places=3, default=0, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockInward',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=24, null=True)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=200)),
                ('supplier_ref', models.CharField(blank=True, default='', max_length=60)),
                ('bill_number', models.CharField(blank=True, default='', max_length=60)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], default='DRAFT', max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('total_cost', common.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cost_pending_lines', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Low stock'), ('OUT_OF_STOCK', 'Out of stock'), ('BACKORDER_DEMAND', 'Shops waiting')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=10)),
                ('opened_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('value_at_open', common.fields.QtyField(decimal_places=3, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=24)),
                ('reason_code', models.CharField(choices=[('COUNT_CORRECTION', 'Stock count correction'), ('DAMAGE', 'Damaged'), ('EXPIRY', 'Expired'), ('THEFT', 'Lost or stolen'), ('OPENING_STOCK', 'Opening stock'), ('OTHER', 'Other')], max_length=20)),
                ('note', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentLine',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_no', models.PositiveSmallIntegerField()),
                ('mode', models.CharField(choices=[('ADD', 'Add'), ('REMOVE', 'Remove'), ('COUNTED', 'Counted')], max_length=8)),
                ('entered_qty', common.fields.QtyField(decimal_places=3, max_digits=14)),
                ('quantity_change', common.fields.QtyField(decimal_places=3, max_digits=14)),
                ('on_hand_before', common.fields.QtyField(decimal_places=3, max_digits=14)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='inventory.stockadjustment')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'ordering': ['line_no'],
                'indexes': [models.Index(fields=['tenant', 'product'], name='adjustment_line_product_idx')],
                'constraints': [models.UniqueConstraint(fields=('adjustment', 'line_no'), name='uniq_adjustment_line_no'), models.CheckConstraint(condition=models.Q(('quantity_change', 0), _negated=True), name='adjustment_line_change_nonzero'), models.CheckConstraint(condition=models.Q(('entered_qty__gt', 0), models.Q(('mode', 'COUNTED'), ('entered_qty', 0)), _connector='OR'), name='adjustment_line_entered')],
            },
        ),
        migrations.CreateModel(
            name='StockInwardLine',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_no', models.PositiveSmallIntegerField()),
                ('entered_unit', models.CharField(choices=[('BASE', 'Base unit'), ('PACK', 'Pack')], default='BASE', max_length=4)),
                ('entered_qty', common.fields.QtyField(decimal_places=3, max_digits=14)),
                ('quantity', common.fields.QtyField(decimal_places=3, max_digits=14)),
                ('unit_cost', common.fields.UnitCostField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('line_cost', common.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cost_status', models.CharField(blank=True, choices=[('SET', 'Cost entered'), ('PENDING', 'Cost pending')], max_length=8, null=True)),
                ('cost_completed_at', models.DateTimeField(blank=True, null=True)),
                ('cost_completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockinward')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'ordering': ['line_no'],
                'indexes': [models.Index(fields=['tenant', 'product'], name='inward_line_product_idx')],
                'constraints': [models.UniqueConstraint(fields=('inward', 'line_no'), name='uniq_inward_line_no'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inward_line_qty_pos'), models.CheckConstraint(condition=models.Q(('entered_qty__gt', 0)), name='inward_line_entered_pos'), models.CheckConstraint(condition=models.Q(('unit_cost__isnull', True), ('unit_cost__gte', 0), _connector='OR'), name='inward_line_cost_nonneg'), models.CheckConstraint(condition=models.Q(('cost_status__isnull', True), models.Q(('cost_status', 'SET'), ('unit_cost__isnull', False)), models.Q(('cost_status', 'PENDING'), ('unit_cost__isnull', True)), _connector='OR'), name='inward_line_cost_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_warehouse_code'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant',), name='uniq_default_warehouse'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(models.F('tenant'), models.F('product'), models.OrderBy(models.F('created_at'), descending=True), name='movement_product_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'reference_type', 'reference_id'], name='movement_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'movement_type', 'created_at'], name='movement_type_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='movement_created_brin'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='movement_qty_pos'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('on_hand_after__gte', 0), ('reserved_after__gte', 0)), name='movement_balances_nonneg'),
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(fields=['tenant', 'warehouse', 'product'], name='stock_level_wh_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse'), name='uniq_stock_level'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_on_hand__gte', 0)), name='stock_on_hand_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_reserved__gte', 0)), name='stock_reserved_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_backordered__gte', 0)), name='stock_backordered_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_reserved__lte', models.F('quantity_on_hand'))), name='stock_reserved_within_on_hand'),
        ),
        migrations.AddIndex(
            model_name='stockinward',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='inward_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stockinward',
            index=models.Index(condition=models.Q(('cost_pending_lines__gt', 0)), fields=['tenant'], name='inward_cost_pending'),
        ),
        migrations.AddConstraint(
            model_name='stockinward',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='uniq_inward_number'),
        ),
        migrations.AddConstraint(
            model_name='stockinward',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'DRAFT'), models.Q(('number__isnull', False), ('posted_at__isnull', False)), _connector='OR'), name='inward_posted_complete'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['tenant', 'status', 'alert_type'], name='stock_alert_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockalert',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('tenant', 'product', 'warehouse', 'alert_type'), name='uniq_open_stock_alert'),
        ),
        migrations.AddConstraint(
            model_name='stockalert',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', True), ('status', 'OPEN')), models.Q(('resolved_at__isnull', False), ('status', 'RESOLVED')), _connector='OR'), name='stock_alert_resolved_at'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['tenant', 'created_at'], name='adjustment_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockadjustment',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='uniq_adjustment_number'),
        ),
        migrations.AddConstraint(
            model_name='stockadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('note', ''), _negated=True), name='adjustment_note_required'),
        ),
        EnableRLS("Warehouse"),
        EnableRLS("StockLevel"),
        EnableRLS("StockMovement"),
        EnableRLS("StockInward"),
        EnableRLS("StockInwardLine"),
        EnableRLS("StockAdjustment"),
        EnableRLS("StockAdjustmentLine"),
        EnableRLS("StockAlert"),
        MakeAppendOnly("StockMovement"),
        MakeAppendOnly("StockAdjustment"),
        MakeAppendOnly("StockAdjustmentLine"),
        migrations.RunSQL(INWARD_GUARD_SQL, INWARD_GUARD_SQL_REVERSE),
        migrations.RunPython(backfill_warehouses_and_levels, migrations.RunPython.noop),
    ]
