# Generated by Django 5.2.17 on 2026-10-01 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockinward_supplier'),
        ('purchasing', '0002_purchase_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinward',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='purchasing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='stockinwardline',
            name='purchase_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='purchasing.purchaseorderline'),
        ),
    ]
