# Generated by Django 5.2.17 on 2026-09-28 18:39

import common.crypto
import common.ids
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from common.db_ops import EnableRLS
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform', '0005_settings_overrides'),
        ('retailers', '0007_whatsapp_consent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.UUIDField()),
                ('event_code', models.CharField(max_length=40)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS')], max_length=8)),
                ('address', models.CharField(blank=True, default='', max_length=254)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('urgent', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Waiting to be sent'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Not sent')], default='PENDING', max_length=8)),
                ('skip_reason', models.CharField(blank=True, choices=[('NO_ADDRESS', 'No email or mobile number'), ('NO_WHATSAPP_OPT_IN', 'The shop has not agreed to WhatsApp'), ('TURNED_OFF', 'Switched off by the recipient'), ('FEATURE_OFF', 'WhatsApp is not enabled'), ('PAUSED', 'Reminders paused for this shop')], default='', max_length=18)),
                ('send_after', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, default='', max_length=30)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=120)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='retailers.retailer')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_no', models.PositiveSmallIntegerField()),
                ('provider', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=8)),
                ('response', models.JSONField(default=dict)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='notifications.notification')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_code', models.CharField(max_length=40)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS')], max_length=8)),
                ('enabled', models.BooleanField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_code', models.CharField(max_length=40)),
                ('recipient', models.CharField(choices=[('SHOP', 'The shop'), ('SALESPERSON', "The shop's salesperson"), ('COLLECTOR', 'The salesman who collected'), ('STAFF_PERMISSION', 'Staff who can…'), ('OWNERS', 'Owners')], max_length=16)),
                ('permission', models.CharField(blank=True, default='', max_length=60)),
                ('channels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS')], max_length=8), default=list, size=None)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_compulsory', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_code', models.CharField(max_length=40)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS')], max_length=8)),
                ('locale', models.CharField(default='en', max_length=5)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField()),
                ('whatsapp_template_name', models.CharField(blank=True, default='', max_length=100)),
                ('whatsapp_language', models.CharField(blank=True, default='', max_length=10)),
                ('whatsapp_category', models.CharField(blank=True, choices=[('UTILITY', 'Utility'), ('MARKETING', 'Marketing'), ('AUTHENTICATION', 'Authentication')], default='', max_length=14)),
                ('variables', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformTemplate',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_code', models.CharField(max_length=40)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS')], max_length=8)),
                ('locale', models.CharField(default='en', max_length=5)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField()),
                ('whatsapp_template_name', models.CharField(blank=True, default='', max_length=100)),
                ('whatsapp_language', models.CharField(blank=True, default='', max_length=10)),
                ('whatsapp_category', models.CharField(blank=True, choices=[('UTILITY', 'Utility'), ('MARKETING', 'Marketing'), ('AUTHENTICATION', 'Authentication')], default='', max_length=14)),
                ('variables', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event_code', 'channel', 'locale'), name='uniq_platform_template')],
            },
        ),
        migrations.CreateModel(
            name='ReminderPause',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=300)),
                ('until', models.DateField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='retailers.retailer')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppSender',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=16)),
                ('display_name', models.CharField(max_length=100)),
                ('credentials', common.crypto.EncryptedTextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(max_length=1000)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('send_whatsapp', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'is_active', 'starts_at'], name='announcement_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('INVOICE', 'Invoice'), ('CREDIT_NOTE', 'Credit note'), ('RECEIPT', 'Receipt'), ('REFUND_VOUCHER', 'Refund voucher'), ('ORDER_CONFIRMATION', 'Order Confirmation')], max_length=18)),
                ('object_id', models.UUIDField()),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'kind', 'object_id'], name='document_link_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'recipient', 'channel', 'read_at'], name='notification_inbox_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='notification_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('event_id', 'recipient', 'channel'), name='uniq_notification_delivery'),
        ),
        migrations.AddIndex(
            model_name='deliveryattempt',
            index=models.Index(fields=['tenant', 'notification'], name='attempt_notification_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(fields=('tenant', 'user', 'event_code', 'channel'), name='uniq_preference'),
        ),
        migrations.AddConstraint(
            model_name='notificationrule',
            constraint=models.UniqueConstraint(fields=('tenant', 'event_code', 'recipient', 'permission'), name='uniq_notification_rule'),
        ),
        migrations.AddConstraint(
            model_name='notificationrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('recipient', 'STAFF_PERMISSION'), _negated=True), models.Q(('permission', ''), _negated=True), _connector='OR'), name='rule_permission_required'),
        ),
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'event_code', 'channel', 'locale'), name='uniq_tenant_template'),
        ),
        migrations.AddConstraint(
            model_name='reminderpause',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('tenant', 'retailer'), name='one_open_reminder_pause'),
        ),
        migrations.AddConstraint(
            model_name='whatsappsender',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant',), name='one_active_whatsapp_sender'),
        ),
        EnableRLS("NotificationTemplate"),
        EnableRLS("NotificationRule"),
        EnableRLS("Notification"),
        EnableRLS("DeliveryAttempt"),
        EnableRLS("NotificationPreference"),
        EnableRLS("DocumentLink"),
        EnableRLS("ReminderPause"),
        EnableRLS("WhatsAppSender"),
        EnableRLS("Announcement"),
    ]
