# Generated by Django 5.2.17 on 2026-09-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_platform_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Waiting to be sent'), ('SENDING', 'Being sent'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Not sent')], default='PENDING', max_length=8),
        ),
    ]
