# Generated by Django 5.2.17 on 2026-09-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_template_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformtemplate',
            name='approval_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformtemplate',
            name='approval_note',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='platformtemplate',
            name='approval_status',
            field=models.CharField(choices=[('NOT_SUBMITTED', 'Not submitted'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_SUBMITTED', max_length=13),
        ),
        migrations.AlterField(
            model_name='notification',
            name='skip_reason',
            field=models.CharField(blank=True, choices=[('NO_ADDRESS', 'No email or mobile number'), ('NO_WHATSAPP_OPT_IN', 'The shop has not agreed to WhatsApp'), ('TURNED_OFF', 'Switched off by the recipient'), ('FEATURE_OFF', 'WhatsApp is not enabled'), ('PAUSED', 'Reminders paused for this shop'), ('NOT_APPROVED', 'Template not approved')], default='', max_length=18),
        ),
    ]
