# Generated by Django 5.2.17 on 2026-09-30 05:15

from django.db import migrations, models

from apps.notifications.defaults import refresh_platform_templates


def texts(apps, schema_editor):
    refresh_platform_templates(
        apps.get_model("notifications", "PlatformTemplate"), ["ewaybill.failed"]
    )



class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_invoice_cancelled_link_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrule',
            name='recipient',
            field=models.CharField(choices=[('SHOP', 'The shop'), ('SALESPERSON', "The shop's salesperson"), ('COLLECTOR', 'The salesman who collected'), ('STAFF_PERMISSION', 'Staff who can…'), ('OWNERS', 'Owners'), ('DISPATCHER', 'The person who dispatched')], max_length=16),
        ),
        migrations.RunPython(texts, migrations.RunPython.noop),
    ]
