# Generated by Django 5.2.17 on 2026-09-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_dispatcher_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrule',
            name='recipient',
            field=models.CharField(choices=[('SHOP', 'The shop'), ('SALESPERSON', "The shop's salesperson"), ('COLLECTOR', 'The salesman who collected'), ('STAFF_PERMISSION', 'Staff who can…'), ('OWNERS', 'Owners'), ('DISPATCHER', 'The person who dispatched'), ('REQUESTER', 'The person who asked')], max_length=16),
        ),
    ]
