# Generated by Django 5.2.17 on 2026-10-01 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_report_texts'),
        ('platform', '0007_purchasing_flag'),
        ('purchasing', '0002_purchase_orders'),
        ('retailers', '0008_retaileraddress_distance_km'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='purchasing.supplier'),
        ),
        migrations.AlterField(
            model_name='documentlink',
            name='kind',
            field=models.CharField(choices=[('INVOICE', 'Invoice'), ('CREDIT_NOTE', 'Credit note'), ('RECEIPT', 'Receipt'), ('REFUND_VOUCHER', 'Refund voucher'), ('ORDER_CONFIRMATION', 'Order Confirmation'), ('PURCHASE_ORDER', 'Purchase order')], max_length=18),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='recipient',
            field=models.CharField(choices=[('SHOP', 'The shop'), ('SALESPERSON', "The shop's salesperson"), ('COLLECTOR', 'The salesman who collected'), ('STAFF_PERMISSION', 'Staff who can…'), ('OWNERS', 'Owners'), ('DISPATCHER', 'The person who dispatched'), ('REQUESTER', 'The person who asked'), ('SUPPLIER', 'The supplier')], max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='audience',
            field=models.CharField(choices=[('SHOP', 'The shop'), ('STAFF', 'Staff'), ('SUPPLIER', 'The supplier')], default='SHOP', max_length=8),
        ),
        migrations.AlterField(
            model_name='platformtemplate',
            name='audience',
            field=models.CharField(choices=[('SHOP', 'The shop'), ('STAFF', 'Staff'), ('SUPPLIER', 'The supplier')], default='SHOP', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier__isnull', False)), fields=('event_id', 'supplier', 'channel'), name='uniq_notification_supplier'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('recipient__isnull', False), ('supplier__isnull', False), _connector='OR'), name='notification_has_recipient'),
        ),
    ]
