# Generated by Django 5.2.17 on 2026-10-03 09:26

import common.ids
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.db_ops import EnableRLS


def push_where_in_app(apps, schema_editor):
    """Owner, 2026-10-03 (ADR-061, §10.2q answer 1): the app notification is on wherever the
    shop's in-app message is. Defaults get it from the catalogue; a distributor's own rules for
    shops get it here."""
    NotificationRule = apps.get_model("notifications", "NotificationRule")
    for rule in NotificationRule.objects.filter(recipient="SHOP", channels__contains=["IN_APP"]):
        if "PUSH" not in rule.channels:
            rule.channels = [*rule.channels, "PUSH"]
            rule.save(update_fields=["channels"])


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0017_language_templates"),
        ("platform", "0010_sms_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="channel",
            field=models.CharField(
                choices=[
                    ("IN_APP", "In-app"),
                    ("EMAIL", "Email"),
                    ("WHATSAPP", "WhatsApp"),
                    ("SMS", "SMS"),
                    ("PUSH", "App notification"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="channel",
            field=models.CharField(
                choices=[
                    ("IN_APP", "In-app"),
                    ("EMAIL", "Email"),
                    ("WHATSAPP", "WhatsApp"),
                    ("SMS", "SMS"),
                    ("PUSH", "App notification"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="notificationrule",
            name="channels",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("IN_APP", "In-app"),
                        ("EMAIL", "Email"),
                        ("WHATSAPP", "WhatsApp"),
                        ("SMS", "SMS"),
                        ("PUSH", "App notification"),
                    ],
                    max_length=8,
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="channel",
            field=models.CharField(
                choices=[
                    ("IN_APP", "In-app"),
                    ("EMAIL", "Email"),
                    ("WHATSAPP", "WhatsApp"),
                    ("SMS", "SMS"),
                    ("PUSH", "App notification"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="platformtemplate",
            name="channel",
            field=models.CharField(
                choices=[
                    ("IN_APP", "In-app"),
                    ("EMAIL", "Email"),
                    ("WHATSAPP", "WhatsApp"),
                    ("SMS", "SMS"),
                    ("PUSH", "App notification"),
                ],
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[("ANDROID", "Android"), ("WEB", "Web")], max_length=8
                    ),
                ),
                ("token", models.CharField(max_length=512)),
                ("app_version", models.CharField(blank=True, default="", max_length=20)),
                ("last_seen_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant", "user", "is_active"], name="device_user_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "token"), name="uniq_device_token")
                ],
            },
        ),
        EnableRLS("DeviceToken"),
        migrations.RunPython(push_where_in_app, migrations.RunPython.noop),
    ]
