# Generated by Django 5.2.17 on 2026-09-25 13:41

import common.fields
import common.ids
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models

from common.db_ops import EnableRLS


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_catalog_models'),
        ('platform', '0005_settings_overrides'),
        ('retailers', '0005_retailer_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, default='', max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percentage'), ('FLAT_PER_UNIT', 'Rupees off per unit')], max_length=15)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('scope_type', models.CharField(choices=[('ALL', 'All products'), ('PRODUCT', 'One product'), ('CATEGORY', 'A category (and its sub-categories)'), ('BRAND', 'A brand')], max_length=10)),
                ('audience_type', models.CharField(choices=[('ALL', 'All shops'), ('PRICE_LIST', 'Shops on a price list'), ('RETAILER', 'One shop')], max_length=12)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stackable', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.category')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.product')),
                ('retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='retailers.retailer')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
                ('price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pricing.pricelist')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', common.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RetailerPrice',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', common.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_prices', to='retailers.retailer')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountSlab',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_qty', common.fields.QtyField(decimal_places=3, max_digits=14)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='pricing.discountrule')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'ordering': ['min_qty'],
                'constraints': [models.UniqueConstraint(fields=('rule', 'min_qty'), name='uniq_slab_min_qty'), models.CheckConstraint(condition=models.Q(('min_qty__gt', 0)), name='slab_min_qty_pos'), models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='slab_value_pos')],
            },
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(models.F('tenant'), django.db.models.functions.text.Lower('name'), condition=models.Q(('deleted_at__isnull', True)), name='uniq_price_list_name'),
        ),
        migrations.AddIndex(
            model_name='discountrule',
            index=models.Index(fields=['tenant', 'is_active', 'scope_type'], name='discount_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='discountrule',
            index=models.Index(fields=['tenant', 'audience_type'], name='discount_audience_idx'),
        ),
        migrations.AddConstraint(
            model_name='discountrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('brand__isnull', True), ('category__isnull', True), ('product__isnull', True), ('scope_type', 'ALL')), models.Q(('brand__isnull', True), ('category__isnull', True), ('product__isnull', False), ('scope_type', 'PRODUCT')), models.Q(('brand__isnull', True), ('category__isnull', False), ('product__isnull', True), ('scope_type', 'CATEGORY')), models.Q(('brand__isnull', False), ('category__isnull', True), ('product__isnull', True), ('scope_type', 'BRAND')), _connector='OR'), name='discount_scope_matches_target'),
        ),
        migrations.AddConstraint(
            model_name='discountrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('audience_type', 'ALL'), ('price_list__isnull', True), ('retailer__isnull', True)), models.Q(('audience_type', 'PRICE_LIST'), ('price_list__isnull', False), ('retailer__isnull', True)), models.Q(('audience_type', 'RETAILER'), ('price_list__isnull', True), ('retailer__isnull', False)), _connector='OR'), name='discount_audience_matches_target'),
        ),
        migrations.AddConstraint(
            model_name='discountrule',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='discount_value_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='discountrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'PERCENT'), _negated=True), ('value__lte', 100), _connector='OR'), name='discount_percent_max_100'),
        ),
        migrations.AddConstraint(
            model_name='discountrule',
            constraint=models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='discount_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='discountrule',
            constraint=models.CheckConstraint(condition=models.Q(('stackable', False)), name='discount_no_stacking_v1'),
        ),
        migrations.AddIndex(
            model_name='pricelistitem',
            index=models.Index(fields=['tenant', 'product'], name='price_list_item_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricelistitem',
            constraint=models.UniqueConstraint(fields=('price_list', 'product'), name='uniq_price_list_item'),
        ),
        migrations.AddConstraint(
            model_name='pricelistitem',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_list_item_nonneg'),
        ),
        migrations.AddIndex(
            model_name='retailerprice',
            index=models.Index(fields=['tenant', 'product'], name='retailer_price_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='retailerprice',
            constraint=models.UniqueConstraint(fields=('retailer', 'product'), name='uniq_retailer_price'),
        ),
        migrations.AddConstraint(
            model_name='retailerprice',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='retailer_price_nonneg'),
        ),
        EnableRLS("PriceList"),
        EnableRLS("PriceListItem"),
        EnableRLS("RetailerPrice"),
        EnableRLS("DiscountRule"),
        EnableRLS("DiscountSlab"),
    ]
