# Generated by Django 5.2.17 on 2026-10-01 19:50

import common.fields
import common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.db_ops import EnableRLS


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform', '0007_purchasing_flag'),
        ('retailers', '0008_retaileraddress_distance_km'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopActivity',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('computed_at', models.DateTimeField()),
                ('segment', models.CharField(choices=[('NEW', 'New'), ('ACTIVE', 'Active'), ('SLOWING', 'Slowing down'), ('DORMANT', 'Stopped ordering'), ('NEVER_ORDERED', 'Never ordered')], max_length=13)),
                ('first_order_date', models.DateField(blank=True, null=True)),
                ('last_order_date', models.DateField(blank=True, null=True)),
                ('days_since_last', models.PositiveIntegerField(blank=True, null=True)),
                ('usual_gap_days', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('orders_90', models.PositiveIntegerField(default=0)),
                ('orders_prev_90', models.PositiveIntegerField(default=0)),
                ('value_90', common.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('value_prev_90', common.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('urgency', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='retailers.retailer')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'segment'], name='shop_activity_segment_idx'), models.Index(fields=['tenant', '-urgency'], name='shop_activity_urgency_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShopContact',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('CALL', 'Call'), ('WHATSAPP', 'WhatsApp'), ('VISIT', 'Visit'), ('OTHER', 'Other')], max_length=8)),
                ('outcome', models.CharField(choices=[('REACHED', 'Spoke to them'), ('NO_ANSWER', 'No answer'), ('WILL_ORDER', 'Will order'), ('NOT_INTERESTED', 'Not interested'), ('OTHER', 'Other')], max_length=14)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='retailers.retailer')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'retailer', '-created_at'], name='shop_contact_retailer_idx')],
            },
        ),
        EnableRLS("ShopActivity"),
        EnableRLS("ShopContact"),
    ]
