# Generated by Django 5.2.17 on 2026-09-25 05:29

import apps.platform.models
import apps.platform.validators
import common.crypto
import common.fields
import common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.db_ops import EnableRLS


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CessType',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('calc_method', models.CharField(choices=[('PERCENT', 'Percentage of taxable value'), ('SPECIFIC_PER_UNIT', 'Fixed amount per unit (reserved)')], default='PERCENT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('default_enabled', models.BooleanField(default=False)),
                ('tenant_toggleable', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='address_line1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tenant',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='gstin',
            field=models.CharField(max_length=15, null=True, unique=True, validators=[apps.platform.validators.validate_gstin]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='legal_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='pan',
            field=models.CharField(max_length=10, null=True, validators=[apps.platform.validators.validate_pan]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(max_length=16, null=True, validators=[apps.platform.validators.validate_business_phone]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='pincode',
            field=models.CharField(max_length=6, null=True, validators=[apps.platform.validators.validate_pincode]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='registration_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('COMPOSITION', 'Composition (reserved)')], default='REGULAR', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='suspended_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenant',
            name='webhook_token',
            field=models.CharField(max_length=64, null=True),  # unique + default after backfill (0004)
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.CharField(max_length=30, unique=True, validators=[apps.platform.validators.validate_tenant_slug]),
        ),
        migrations.CreateModel(
            name='HsnRateHint',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hsn_prefix', models.CharField(max_length=8, validators=[apps.platform.validators.validate_hsn_prefix])),
                ('gst_rate', common.fields.RateField(decimal_places=3, max_digits=6)),
                ('effective_from', models.DateField()),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['hsn_prefix', '-effective_from'],
                'constraints': [models.UniqueConstraint(fields=('hsn_prefix', 'effective_from'), name='uniq_hsn_hint_prefix_date'), models.CheckConstraint(condition=models.Q(('hsn_prefix__regex', '^[0-9]{2,8}$')), name='hsn_hint_prefix_digits')],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('price_monthly', common.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('max_retailers', models.PositiveIntegerField(blank=True, null=True)),
                ('max_staff', models.PositiveIntegerField(blank=True, null=True)),
                ('max_products', models.PositiveIntegerField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['price_monthly', 'code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='uniq_default_plan'), models.CheckConstraint(condition=models.Q(('price_monthly__gte', 0)), name='plan_price_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('is_union_territory', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('code__regex', '^[0-9]{2}$')), name='state_code_2_digits')],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.state'),
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', common.fields.RateField(decimal_places=3, max_digits=6, unique=True)),
                ('label', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['rate'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('rate__lte', 100)), name='tax_rate_0_to_100')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.plan')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('tenant',), name='uniq_current_subscription')],
            },
        ),
        migrations.CreateModel(
            name='TenantBranding',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('logo', models.CharField(blank=True, default='', max_length=255)),
                ('favicon', models.CharField(blank=True, default='', max_length=255)),
                ('app_icon', models.CharField(blank=True, default='', max_length=255)),
                ('primary_color', models.CharField(default='#2f5bea', max_length=7, validators=[apps.platform.validators.validate_hex_color])),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='uniq_branding_per_tenant'), models.CheckConstraint(condition=models.Q(('primary_color__regex', '^#[0-9a-f]{6}$')), name='branding_color_hex')],
            },
        ),
        migrations.CreateModel(
            name='TenantFeature',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='platform.featureflag')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'flag'), name='uniq_tenant_feature')],
            },
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_terms', models.TextField(blank=True, default='')),
                ('invoice_footer', models.TextField(blank=True, default='')),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=200)),
                ('bank_account_number', common.crypto.EncryptedTextField(blank=True, default='')),
                ('bank_ifsc', models.CharField(blank=True, default='', max_length=11, validators=[apps.platform.validators.validate_ifsc])),
                ('bank_name', models.CharField(blank=True, default='', max_length=120)),
                ('bank_branch', models.CharField(blank=True, default='', max_length=120)),
                ('upi_id', models.CharField(blank=True, default='', max_length=320, validators=[apps.platform.validators.validate_upi_id])),
                ('signatory_name', models.CharField(blank=True, default='', max_length=150)),
                ('signatory_image', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='uniq_profile_per_tenant')],
            },
        ),
        EnableRLS("Subscription"),
        EnableRLS("TenantBranding"),
        EnableRLS("TenantFeature"),
        EnableRLS("TenantProfile"),
    ]
