# Generated by Django 5.2.17 on 2026-09-25 05:30

import apps.platform.models
import apps.platform.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0003_seed_reference_data_and_backfill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='tenant',
            name='address_line1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='gstin',
            field=models.CharField(max_length=15, unique=True, validators=[apps.platform.validators.validate_gstin]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='legal_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='pan',
            field=models.CharField(max_length=10, validators=[apps.platform.validators.validate_pan]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(max_length=16, validators=[apps.platform.validators.validate_business_phone]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='pincode',
            field=models.CharField(max_length=6, validators=[apps.platform.validators.validate_pincode]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.state'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='webhook_token',
            field=models.CharField(default=apps.platform.models.new_webhook_token, max_length=64, unique=True),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '^[a-z0-9][a-z0-9-]{1,28}[a-z0-9]$')), name='tenant_slug_format'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ONBOARDING', 'ACTIVE', 'SUSPENDED'])), name='tenant_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(('registration_type', 'REGULAR')), name='tenant_registration_regular'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(('gstin__regex', '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$')), name='tenant_gstin_format'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(('gstin__startswith', models.F('state_id'))), name='tenant_gstin_matches_state'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(('pan', django.db.models.functions.text.Substr('gstin', 3, 10))), name='tenant_pan_matches_gstin'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(('pincode__regex', '^[1-9][0-9]{5}$')), name='tenant_pincode_format'),
        ),
    ]
