# Generated by Django 5.2.17 on 2026-10-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0009_text_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='sms_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
