# Generated by Django 5.2.17 on 2026-09-27 10:55

import common.fields
import common.ids
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models

from common.db_ops import EnableRLS, MakeAppendOnly


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_own_brand_cost_price'),
        ('inventory', '0001_inventory_models'),
        ('platform', '0005_settings_overrides'),
        ('pricing', '0001_initial'),
        ('retailers', '0006_retailer_price_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='retailers.retailer')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartLine',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', common.fields.QtyField(decimal_places=3, max_digits=14)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.cart')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=24)),
                ('placed_via', models.CharField(choices=[('RETAILER_APP', 'Shop app'), ('STAFF', 'Staff')], max_length=14)),
                ('status', models.CharField(choices=[('PLACED', 'Placed'), ('ON_HOLD', 'On hold'), ('ACCEPTED', 'Accepted'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=12)),
                ('backorder_state', models.CharField(choices=[('NONE', 'None'), ('OPEN', 'Open'), ('CLOSED', 'Closed')], default='NONE', max_length=6)),
                ('hold_reason', models.CharField(blank=True, choices=[('CREDIT_LIMIT', 'Over the credit limit'), ('OVERDUE', 'Overdue invoices')], default='', max_length=14)),
                ('settings_snapshot', models.JSONField(default=dict)),
                ('shipping_address', models.JSONField(default=dict)),
                ('billing_address', models.JSONField(default=dict)),
                ('supply_type', models.CharField(max_length=5)),
                ('prices_include_tax', models.BooleanField(default=False)),
                ('gross_total', common.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('discount_total', common.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('taxable_total', common.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('tax_total', common.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('round_off', common.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('grand_total', common.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('retailer_note', models.CharField(blank=True, default='', max_length=500)),
                ('internal_note', models.TextField(blank=True, default='')),
                ('placed_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=500)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=500)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('place_of_supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.state')),
                ('placed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='retailers.retailer')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'ordering': ['-placed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Fulfilment',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=28)),
                ('kind', models.CharField(choices=[('INITIAL', 'First shipment'), ('BACKORDER', 'Backorder shipment')], max_length=10)),
                ('status', models.CharField(choices=[('ALLOCATED', 'To pack'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='ALLOCATED', max_length=10)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=20)),
                ('transporter_name', models.CharField(blank=True, default='', max_length=120)),
                ('lr_number', models.CharField(blank=True, default='', max_length=40)),
                ('packed_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouse')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfilments', to='orders.order')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_no', models.PositiveSmallIntegerField()),
                ('product_code', models.CharField(max_length=40)),
                ('product_name', models.CharField(max_length=200)),
                ('hsn_code', models.CharField(max_length=8)),
                ('unit_code', models.CharField(max_length=10)),
                ('base_price', common.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('unit_price', common.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('price_source', models.CharField(max_length=12)),
                ('discount_per_unit', common.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('gst_rate', common.fields.RateField(decimal_places=3, max_digits=6)),
                ('cess_rate', common.fields.RateField(decimal_places=3, default=0, max_digits=6)),
                ('qty_ordered', common.fields.QtyField(decimal_places=3, max_digits=14)),
                ('qty_pending', common.fields.QtyField(decimal_places=3, default=0, max_digits=14)),
                ('qty_reserved', common.fields.QtyField(decimal_places=3, default=0, max_digits=14)),
                ('qty_backordered', common.fields.QtyField(decimal_places=3, default=0, max_digits=14)),
                ('qty_allocated', common.fields.QtyField(decimal_places=3, default=0, max_digits=14)),
                ('qty_cancelled', common.fields.QtyField(decimal_places=3, default=0, max_digits=14)),
                ('qty_dispatched', common.fields.QtyField(decimal_places=3, default=0, max_digits=14)),
                ('qty_delivered', common.fields.QtyField(decimal_places=3, default=0, max_digits=14)),
                ('gross_amount', common.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('discount_amount', common.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('taxable_amount', common.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', common.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('line_total', common.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'ordering': ['line_no'],
            },
        ),
        migrations.CreateModel(
            name='FulfilmentLine',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', common.fields.QtyField(decimal_places=3, max_digits=14)),
                ('qty_packed', common.fields.QtyField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('unit_price', common.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('price_source', models.CharField(choices=[('ORDER_SNAPSHOT', 'Order price'), ('REPRICED', "Today's price")], default='ORDER_SNAPSHOT', max_length=14)),
                ('price_increased', models.BooleanField(default=False)),
                ('cancelled_by_retailer_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fulfilment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='orders.fulfilment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orders.orderline')),
            ],
        ),
        migrations.CreateModel(
            name='BackorderAllocation',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', common.fields.QtyField(decimal_places=3, max_digits=14)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('SKIPPED_CREDIT', 'Skipped: over credit limit')], max_length=15)),
                ('trigger', models.CharField(choices=[('INWARD', 'Goods received'), ('ADJUSTMENT_IN', 'Stock added'), ('RELEASE', 'Stock released'), ('MANUAL', 'Manual')], max_length=14)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouse')),
                ('fulfilment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orders.fulfilment')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='orders.orderline')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderLineDiscount',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('rule_name', models.CharField(max_length=120)),
                ('discount_type', models.CharField(max_length=16)),
                ('value', common.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('amount', common.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='orders.orderline')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pricing.discountrule')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, default='', max_length=12)),
                ('to_status', models.CharField(max_length=12)),
                ('event', models.CharField(choices=[('PLACE', 'Placed'), ('HOLD', 'Put on hold'), ('APPROVE_HOLD', 'Hold approved'), ('ACCEPT', 'Accepted'), ('REJECT', 'Rejected'), ('CANCEL', 'Cancelled'), ('MODIFY', 'Changed'), ('PACK', 'Packed'), ('DISPATCH', 'Dispatched'), ('DELIVER', 'Delivered'), ('SHORT_SUPPLY', 'Short supplied'), ('BACKORDER_ALLOCATED', 'Backorder allocated'), ('BACKORDER_CANCELLED', 'Backorder cancelled'), ('COMPLETE', 'Completed')], max_length=20)),
                ('actor_type', models.CharField(choices=[('RETAILER', 'Shop'), ('STAFF', 'Staff'), ('SYSTEM', 'System')], max_length=8)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('payload', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='orders.order')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('retailer', 'user'), name='uniq_cart_per_user'),
        ),
        migrations.AddConstraint(
            model_name='cartline',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='uniq_cart_product'),
        ),
        migrations.AddConstraint(
            model_name='cartline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='cart_line_qty_pos'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(models.F('tenant'), models.F('status'), models.OrderBy(models.F('placed_at'), descending=True), name='order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(models.F('tenant'), models.F('retailer'), models.OrderBy(models.F('placed_at'), descending=True), name='order_retailer_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'backorder_state'], name='order_backorder_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='uniq_order_number'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('gross_total__gte', 0), ('discount_total__gte', 0), ('taxable_total__gte', 0), ('tax_total__gte', 0), ('grand_total__gte', 0)), name='order_totals_nonneg'),
        ),
        migrations.AddIndex(
            model_name='fulfilment',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='fulfilment_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='fulfilment',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='uniq_fulfilment_number'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(condition=models.Q(('qty_backordered__gt', 0)), fields=['tenant', 'product', 'created_at'], name='order_line_backorder_queue'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.UniqueConstraint(fields=('order', 'line_no'), name='uniq_order_line_no'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_ordered', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('qty_pending'), '+', models.F('qty_reserved')), '+', models.F('qty_backordered')), '+', models.F('qty_allocated')), '+', models.F('qty_cancelled')))), name='order_line_qty_buckets'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_ordered__gt', 0), ('qty_pending__gte', 0), ('qty_reserved__gte', 0), ('qty_backordered__gte', 0), ('qty_allocated__gte', 0), ('qty_cancelled__gte', 0), ('qty_dispatched__gte', 0), ('qty_delivered__gte', 0)), name='order_line_qty_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_dispatched__lte', models.F('qty_allocated')), ('qty_delivered__lte', models.F('qty_dispatched'))), name='order_line_shipped_within_allocated'),
        ),
        migrations.AddConstraint(
            model_name='fulfilmentline',
            constraint=models.UniqueConstraint(fields=('fulfilment', 'order_line'), name='uniq_fulfilment_line'),
        ),
        migrations.AddConstraint(
            model_name='fulfilmentline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='fulfilment_line_qty_pos'),
        ),
        migrations.AddConstraint(
            model_name='fulfilmentline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_packed__isnull', True), models.Q(('qty_packed__gte', 0), ('qty_packed__lte', models.F('quantity'))), _connector='OR'), name='fulfilment_line_packed_within'),
        ),
        migrations.AddIndex(
            model_name='backorderallocation',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='allocation_status_idx'),
        ),
        migrations.AddIndex(
            model_name='backorderallocation',
            index=models.Index(fields=['tenant', 'order_line'], name='allocation_line_idx'),
        ),
        migrations.AddConstraint(
            model_name='backorderallocation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='allocation_qty_pos'),
        ),
        migrations.AddConstraint(
            model_name='orderlinediscount',
            constraint=models.UniqueConstraint(fields=('order_line', 'position'), name='uniq_order_line_discount'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['tenant', 'order', 'created_at'], name='order_history_idx'),
        ),
        EnableRLS("Cart"),
        EnableRLS("CartLine"),
        EnableRLS("Order"),
        EnableRLS("OrderLine"),
        EnableRLS("OrderLineDiscount"),
        EnableRLS("OrderStatusHistory"),
        EnableRLS("Fulfilment"),
        EnableRLS("FulfilmentLine"),
        EnableRLS("BackorderAllocation"),
        MakeAppendOnly("OrderStatusHistory"),
    ]
