# Generated by Django 5.2.17 on 2026-09-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_orders_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='placed_by_label',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
