# Generated by Django 5.2.17 on 2026-09-27 19:00

import common.fields
from django.db import migrations, models


def partly_delivered(apps, schema_editor):
    """DELIVERED is gone: an order with a delivered shipment and more to follow is PARTLY_DELIVERED
    (2026-09-28). The append-only timeline keeps what it recorded."""
    Order = apps.get_model("orders", "Order")
    Order.objects.filter(status="DELIVERED").update(status="PARTLY_DELIVERED")


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_placed_by_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credit_approved_value',
            field=common.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='backorderallocation',
            name='status',
            field=models.CharField(choices=[('PROPOSED', 'Proposed'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('SKIPPED_CREDIT', 'Skipped: over credit limit'), ('SKIPPED_BLOCKED', 'Skipped: shop blocked')], max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('ON_HOLD', 'On hold'), ('ACCEPTED', 'Accepted'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('PARTLY_DELIVERED', 'Partly delivered'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=16),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='from_status',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='to_status',
            field=models.CharField(max_length=16),
        ),
        migrations.RunPython(partly_delivered, migrations.RunPython.noop),
    ]
