# Generated by Django 5.2.17 on 2026-09-28 11:12

import common.fields
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_own_brand_cost_price'),
        ('orders', '0003_partly_delivered_and_hold_approval'),
        ('platform', '0005_settings_overrides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='qty_invoiced',
            field=common.fields.QtyField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_invoiced__gte', 0), ('qty_invoiced__lte', django.db.models.expressions.CombinedExpression(models.F('qty_ordered'), '-', models.F('qty_cancelled')))), name='order_line_invoiced_within_open'),
        ),
    ]
