# Generated by Django 5.2.17 on 2026-09-28 11:27

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_qty_invoiced'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfilmentline',
            name='discount_amount',
            field=common.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
