# Generated by Django 5.2.17 on 2026-09-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_fulfilment_line_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backorderallocation',
            name='trigger',
            field=models.CharField(choices=[('INWARD', 'Goods received'), ('ADJUSTMENT_IN', 'Stock added'), ('RELEASE', 'Stock released'), ('RETURN', 'Goods returned'), ('MANUAL', 'Manual')], max_length=14),
        ),
    ]
