# Generated by Django 5.2.17 on 2026-09-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_return_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatushistory',
            name='event',
            field=models.CharField(choices=[('PLACE', 'Placed'), ('HOLD', 'Put on hold'), ('APPROVE_HOLD', 'Hold approved'), ('ACCEPT', 'Accepted'), ('REJECT', 'Rejected'), ('CANCEL', 'Cancelled'), ('MODIFY', 'Changed'), ('PACK', 'Packed'), ('DISPATCH', 'Dispatched'), ('DELIVER', 'Delivered'), ('SHORT_SUPPLY', 'Short supplied'), ('BACKORDER_ALLOCATED', 'Backorder allocated'), ('BACKORDER_CANCELLED', 'Backorder cancelled'), ('COMPLETE', 'Completed'), ('TAKE_BACK', 'Goods taken back')], max_length=20),
        ),
    ]
