# Generated by Django 5.2.17 on 2026-09-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_take_back_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfilment',
            name='distance_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
