# Generated by Django 5.2.17 on 2026-09-30 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def shops_salesperson(apps, schema_editor):
    """Orders placed before Phase 8 take the shop's salesperson now (ADR-050 item 4)."""
    Order = apps.get_model("orders", "Order")
    Retailer = apps.get_model("retailers", "Retailer")
    Order.objects.filter(salesperson__isnull=True).update(
        salesperson=Subquery(
            Retailer.objects.filter(pk=OuterRef("retailer_id")).values("salesperson_id")[:1]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_fulfilment_distance_km'),
        ('platform', '0005_settings_overrides'),
        ('retailers', '0008_retaileraddress_distance_km'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(models.F('tenant'), models.F('salesperson'), models.OrderBy(models.F('placed_at'), descending=True), name='order_salesperson_idx'),
        ),
        migrations.RunPython(shops_salesperson, migrations.RunPython.noop),
    ]
