# Generated by Django 5.2.17 on 2026-09-25 06:35

import common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.db_ops import EnableRLS


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform', '0005_settings_overrides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, default='', max_length=150)),
                ('phone', models.CharField(max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RetailerUser',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logins', to='retailers.retailer')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='retailer_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='retailer',
            index=models.Index(fields=['tenant', 'shop_name'], name='retailer_tenant_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='retailer',
            constraint=models.UniqueConstraint(fields=('tenant', 'phone'), name='uniq_retailer_phone_per_tenant'),
        ),
        EnableRLS("Retailer"),
        EnableRLS("RetailerUser"),
    ]
