# Generated by Django 5.2.17 on 2026-09-25 13:27

import common.fields
import common.ids
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models

from common.db_ops import EnableRLS


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0005_settings_overrides'),
        ('retailers', '0002_rename_stub_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerAddress',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('BILLING', 'Billing'), ('SHIPPING', 'Shipping')], max_length=10)),
                ('label', models.CharField(blank=True, default='', max_length=60)),
                ('line1', models.CharField(max_length=200)),
                ('line2', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['kind', '-is_default', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='retailer',
            options={'ordering': ['shop_name']},
        ),
        migrations.AddField(
            model_name='retailer',
            name='blocked_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='retailer',
            name='code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='retailer',
            name='credit_limit',
            field=common.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='retailer',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='retailer',
            name='pan',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='retailer',
            name='payment_terms_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='retailer',
            name='preferred_language',
            field=models.CharField(default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='retailer',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retailer',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.state'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'On hold')], default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='retailer',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='retailer',
            name='welcome_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='retailer',
            index=models.Index(fields=['tenant', 'salesperson'], name='retailer_salesperson_idx'),
        ),
        migrations.AddIndex(
            model_name='retailer',
            index=models.Index(fields=['tenant', 'status'], name='retailer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='retailer',
            index=django.contrib.postgres.indexes.GinIndex(fields=['shop_name'], name='retailer_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddField(
            model_name='retaileraddress',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retaileraddress',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='retailers.retailer'),
        ),
        migrations.AddField(
            model_name='retaileraddress',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.state'),
        ),
        migrations.AddField(
            model_name='retaileraddress',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant'),
        ),
        migrations.AddConstraint(
            model_name='retaileraddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('retailer', 'kind'), name='uniq_default_address_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='retaileraddress',
            constraint=models.CheckConstraint(condition=models.Q(('pincode__regex', '^[1-9][0-9]{5}$')), name='retailer_address_pincode'),
        ),
        EnableRLS("RetailerAddress"),
    ]
