# Generated by Django 5.2.17 on 2026-09-25 13:27

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0005_settings_overrides'),
        ('retailers', '0004_backfill_codes_and_states'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.state'),
        ),
        migrations.AddConstraint(
            model_name='retailer',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_retailer_code'),
        ),
        migrations.AddConstraint(
            model_name='retailer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'mobile'), name='uniq_retailer_mobile_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='retailer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('gstin__isnull', False)), fields=('tenant', 'gstin'), name='uniq_retailer_gstin_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='retailer',
            constraint=models.CheckConstraint(condition=models.Q(('gstin__isnull', True), ('gstin__startswith', models.F('state_id')), _connector='OR'), name='retailer_gstin_matches_state'),
        ),
        migrations.AddConstraint(
            model_name='retailer',
            constraint=models.CheckConstraint(condition=models.Q(('gstin__isnull', True), ('pan', django.db.models.functions.text.Substr('gstin', 3, 10)), _connector='OR'), name='retailer_pan_matches_gstin'),
        ),
        migrations.AddConstraint(
            model_name='retailer',
            constraint=models.CheckConstraint(condition=models.Q(('credit_limit__isnull', True), ('credit_limit__gte', 0), _connector='OR'), name='retailer_credit_limit_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='retailer',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'BLOCKED'])), name='retailer_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='retailer',
            constraint=models.CheckConstraint(condition=models.Q(('mobile__regex', '^\\+91[6-9][0-9]{9}$')), name='retailer_mobile_format'),
        ),
    ]
