# Generated by Django 5.2.17 on 2026-09-25 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        ('retailers', '0005_retailer_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pricing.pricelist'),
        ),
    ]
