# Generated by Django 5.2.17 on 2026-09-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0006_retailer_price_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='whatsapp_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='retailer',
            name='whatsapp_opt_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='whatsapp_opt_in_source',
            field=models.CharField(blank=True, choices=[('SHOP_APP', 'The shop, in the app'), ('STAFF', 'Staff'), ('IMPORT', 'Import')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='retailer',
            name='whatsapp_opt_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='whatsapp_prompted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
