# Generated by Django 5.2.17 on 2026-10-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0008_retaileraddress_distance_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='preferred_language',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        # ADR-060 (owner, question 5): shops saved as English because it was the default now
        # follow the distributor's default (English unless it changes); Hindi and Marathi stay.
        migrations.RunSQL(
            "UPDATE retailers_retailer SET preferred_language = '' WHERE preferred_language = 'en'",
            reverse_sql=(
                "UPDATE retailers_retailer SET preferred_language = 'en' "
                "WHERE preferred_language = ''"
            ),
        ),
    ]
