# Generated by Django 5.2.17 on 2026-10-02 14:28

import common.search_keys
import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_search_key'),
        ('platform', '0008_free_goods_flag'),
        ('pricing', '0002_free_goods'),
        ('retailers', '0009_languages_from_manifest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='owner_name_key',
            field=models.GeneratedField(db_persist=True, expression=common.search_keys.SearchKey('owner_name'), output_field=models.TextField()),
        ),
        migrations.AddField(
            model_name='retailer',
            name='shop_name_key',
            field=models.GeneratedField(db_persist=True, expression=common.search_keys.SearchKey('shop_name'), output_field=models.TextField()),
        ),
        migrations.AddIndex(
            model_name='retailer',
            index=django.contrib.postgres.indexes.GinIndex(fields=['shop_name_key'], name='retailer_name_key_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
