"""ADR-059: the data assistant's questions (tenant-scoped, RLS)."""

# Generated by Django 5.2.17 on 2026-10-02 02:00

import common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.db_ops import EnableRLS


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_ai_foundation'),
        ('platform', '0008_free_goods_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantQuestion',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Being answered'), ('ANSWERED', 'Answered'), ('FAILED', "Couldn't answer"), ('LIMITED', 'Monthly allowance used up')], default='PENDING', max_length=8)),
                ('answer', models.TextField(blank=True, default='')),
                ('tools', models.JSONField(blank=True, default=list)),
                ('units_in', models.PositiveIntegerField(default=0)),
                ('units_out', models.PositiveIntegerField(default=0)),
                ('rounds', models.PositiveSmallIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, default='', max_length=200)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'user', '-created_at'], name='ai_question_user_idx')],
            },
        ),
        EnableRLS("AssistantQuestion"),
    ]
