# Generated by Django 5.2.17 on 2026-10-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_assistant_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantquestion',
            name='model',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
