# Generated by Django 5.2.17 on 2026-09-25 05:46

import common.ids
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.db_ops import EnableRLS, MakeAppendOnly


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform', '0004_tenant_required_fields_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_type', models.CharField(choices=[('PLATFORM', 'Platform'), ('STAFF', 'Staff'), ('RETAILER', 'Retailer'), ('SYSTEM', 'System')], max_length=10)),
                ('impersonation_session_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=80)),
                ('target_type', models.CharField(blank=True, default='', max_length=80)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('target_repr', models.CharField(blank=True, default='', max_length=200)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('impersonator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='audit_tenant_created_idx'), models.Index(fields=['tenant', 'target_type', 'target_id'], name='audit_tenant_target_idx'), models.Index(fields=['actor', 'created_at'], name='audit_actor_created_idx'), models.Index(fields=['tenant', 'action', '-created_at'], name='audit_tenant_action_idx'), django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='audit_created_brin')],
                'constraints': [models.CheckConstraint(condition=models.Q(('actor_type__in', ['PLATFORM', 'STAFF', 'RETAILER', 'SYSTEM'])), name='audit_actor_type_valid'), models.CheckConstraint(condition=models.Q(('actor__isnull', False), ('actor_type', 'SYSTEM'), _connector='OR'), name='audit_actor_required_unless_system')],
            },
        ),
        EnableRLS("AuditLog", null_tenant_insertable=True),
        MakeAppendOnly("AuditLog"),
    ]
