# Generated by Django 5.2.17 on 2026-09-28 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_billing_documents'),
        ('platform', '0005_settings_overrides'),
        ('retailers', '0006_retailer_price_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='creditnote',
            name='credit_note_application',
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.CheckConstraint(condition=models.Q(('applied_to_invoice__gte', 0), ('applied_to_invoice__lte', models.F('grand_total')), ('unapplied_amount__gte', 0), ('unapplied_amount__lte', models.F('grand_total'))), name='credit_note_application'),
        ),
    ]
