# Generated by Django 5.2.17 on 2026-09-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_credit_note_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentseries',
            name='document_type',
            field=models.CharField(choices=[('INVOICE', 'Tax invoice'), ('CREDIT_NOTE', 'Credit note'), ('RECEIPT', 'Payment receipt'), ('REFUND', 'Refund voucher')], max_length=12),
        ),
    ]
