# Generated by Django 5.2.17 on 2026-09-29 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_refund_series'),
        ('orders', '0006_return_trigger'),
        ('platform', '0005_settings_overrides'),
        ('retailers', '0007_whatsapp_consent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='fulfilment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='orders.fulfilment'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ISSUED')), fields=('fulfilment',), name='uniq_issued_invoice_per_shipment'),
        ),
    ]
