# Generated by Django 5.2.17 on 2026-09-30 13:59

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_reissued_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='unit_cost',
            field=common.fields.UnitCostField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
