# Generated by Django 5.2.17 on 2026-10-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_return_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='document_language',
            field=models.CharField(default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='document_language',
            field=models.CharField(default='en', max_length=5),
        ),
    ]
