"""Stable, machine-readable error codes. The frontend maps each code to a translated message
(`web/messages/*.json` → `errors.<CODE>`). Never rename a code; add new ones instead."""

from enum import StrEnum


class ErrorCode(StrEnum):
    # generic / transport
    VALIDATION_ERROR = "VALIDATION_ERROR"
    PARSE_ERROR = "PARSE_ERROR"
    NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    NOT_FOUND = "NOT_FOUND"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    NOT_ACCEPTABLE = "NOT_ACCEPTABLE"
    UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE"
    THROTTLED = "THROTTLED"
    CONFLICT = "CONFLICT"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    # tenancy
    TENANT_CONTEXT_MISSING = "TENANT_CONTEXT_MISSING"
    CROSS_TENANT_ACCESS = "CROSS_TENANT_ACCESS"
    # reliability
    IDEMPOTENCY_KEY_REQUIRED = "IDEMPOTENCY_KEY_REQUIRED"
    IDEMPOTENCY_KEY_INVALID = "IDEMPOTENCY_KEY_INVALID"
    IDEMPOTENCY_KEY_REUSED = "IDEMPOTENCY_KEY_REUSED"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    # authentication & sessions
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    RATE_LIMITED = "RATE_LIMITED"
    TENANT_UNAVAILABLE = "TENANT_UNAVAILABLE"
    TOKEN_INVALID = "TOKEN_INVALID"  # noqa: S105 - an error code, not a secret
    SESSION_EXPIRED = "SESSION_EXPIRED"
    MFA_INVALID_CODE = "MFA_INVALID_CODE"
    MFA_REQUIRED_BY_POLICY = "MFA_REQUIRED_BY_POLICY"
    OTP_INVALID = "OTP_INVALID"
    RETAILER_ON_HOLD = "RETAILER_ON_HOLD"
    # staff & plans
    PLAN_LIMIT_REACHED = "PLAN_LIMIT_REACHED"
    LAST_OWNER = "LAST_OWNER"
    ALREADY_A_MEMBER = "ALREADY_A_MEMBER"
    # platform
    SLUG_CHANGE_NOT_CONFIRMED = "SLUG_CHANGE_NOT_CONFIRMED"
    IMPERSONATION_READ_ONLY = "IMPERSONATION_READ_ONLY"
    IMPERSONATION_BLOCKED = "IMPERSONATION_BLOCKED"
    # catalog
    IN_USE = "IN_USE"
    CATEGORY_TOO_DEEP = "CATEGORY_TOO_DEEP"
    TAX_RATE_NOT_CANCELLABLE = "TAX_RATE_NOT_CANCELLABLE"
    PREVIEW_OUT_OF_DATE = "PREVIEW_OUT_OF_DATE"
    # pricing
    PRICE_UNAVAILABLE = "PRICE_UNAVAILABLE"
