"""Stable, machine-readable error codes. The frontend maps each code to a translated message
(`web/messages/*.json` → `errors.<CODE>`). Never rename a code; add new ones instead."""

from enum import StrEnum


class ErrorCode(StrEnum):
    # generic / transport
    VALIDATION_ERROR = "VALIDATION_ERROR"
    PARSE_ERROR = "PARSE_ERROR"
    NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    NOT_FOUND = "NOT_FOUND"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    NOT_ACCEPTABLE = "NOT_ACCEPTABLE"
    UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE"
    THROTTLED = "THROTTLED"
    CONFLICT = "CONFLICT"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    # tenancy
    TENANT_CONTEXT_MISSING = "TENANT_CONTEXT_MISSING"
    CROSS_TENANT_ACCESS = "CROSS_TENANT_ACCESS"
    # reliability
    IDEMPOTENCY_KEY_REQUIRED = "IDEMPOTENCY_KEY_REQUIRED"
    IDEMPOTENCY_KEY_INVALID = "IDEMPOTENCY_KEY_INVALID"
    IDEMPOTENCY_KEY_REUSED = "IDEMPOTENCY_KEY_REUSED"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    MODULE_NOT_ENABLED = "MODULE_NOT_ENABLED"  # an optional module that is switched off
    OVER_RECEIPT = "OVER_RECEIPT"  # more received than ordered, beyond the tolerance (ADR-053)
    WRONG_DELIVERY_CODE = "WRONG_DELIVERY_CODE"  # not the shipment's delivery code (ADR-057)
    DELIVERY_CODE_LOCKED = "DELIVERY_CODE_LOCKED"  # too many wrong codes for now (ADR-057)
    ASSISTANT_RATE_LIMITED = "ASSISTANT_RATE_LIMITED"  # too many questions this hour (ADR-059)
    ASSISTANT_NOT_AVAILABLE = "ASSISTANT_NOT_AVAILABLE"  # no report the assistant may use
    # authentication & sessions
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    RATE_LIMITED = "RATE_LIMITED"
    TENANT_UNAVAILABLE = "TENANT_UNAVAILABLE"
    TOKEN_INVALID = "TOKEN_INVALID"  # noqa: S105 - an error code, not a secret
    APP_UPDATE_REQUIRED = "APP_UPDATE_REQUIRED"  # the Android app is older than allowed (ADR-061)
    SESSION_EXPIRED = "SESSION_EXPIRED"
    MFA_INVALID_CODE = "MFA_INVALID_CODE"
    MFA_REQUIRED_BY_POLICY = "MFA_REQUIRED_BY_POLICY"
    OTP_INVALID = "OTP_INVALID"
    RETAILER_ON_HOLD = "RETAILER_ON_HOLD"
    # staff & plans
    PLAN_LIMIT_REACHED = "PLAN_LIMIT_REACHED"
    LAST_OWNER = "LAST_OWNER"
    ALREADY_A_MEMBER = "ALREADY_A_MEMBER"
    # platform
    SLUG_CHANGE_NOT_CONFIRMED = "SLUG_CHANGE_NOT_CONFIRMED"
    IMPERSONATION_READ_ONLY = "IMPERSONATION_READ_ONLY"
    IMPERSONATION_BLOCKED = "IMPERSONATION_BLOCKED"
    # catalog
    IN_USE = "IN_USE"
    CATEGORY_TOO_DEEP = "CATEGORY_TOO_DEEP"
    TAX_RATE_NOT_CANCELLABLE = "TAX_RATE_NOT_CANCELLABLE"
    PREVIEW_OUT_OF_DATE = "PREVIEW_OUT_OF_DATE"
    # pricing
    PRICE_UNAVAILABLE = "PRICE_UNAVAILABLE"
    # inventory
    INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK"
    STOCK_RESERVED = "STOCK_RESERVED"
    # orders
    CART_NOT_READY = "CART_NOT_READY"
    PRICE_CHANGED = "PRICE_CHANGED"
    CREDIT_LIMIT_EXCEEDED = "CREDIT_LIMIT_EXCEEDED"
    OVERDUE_INVOICES = "OVERDUE_INVOICES"
    GST_IDENTITY_LOCKED = "GST_IDENTITY_LOCKED"
    # payments
    PAYMENT_EXCEEDS_OUTSTANDING = "PAYMENT_EXCEEDS_OUTSTANDING"
    REFUND_EXCEEDS_CREDIT = "REFUND_EXCEEDS_CREDIT"
    # compliance
    GST_CREDENTIALS_NOT_READY = "GST_CREDENTIALS_NOT_READY"
    # online payments
    PAYMENT_GATEWAY_NOT_READY = "PAYMENT_GATEWAY_NOT_READY"
    PAYMENT_GATEWAY_UNAVAILABLE = "PAYMENT_GATEWAY_UNAVAILABLE"
    PAY_PAGE_CLOSED = "PAY_PAGE_CLOSED"  # the app's browser payment page has ended (ADR-061)
