# Generated by Django 5.2.17 on 2026-09-25 12:37

import common.fields
import common.ids
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models

from apps.catalog.defaults import DEFAULT_UNITS
from common.db_ops import EnableRLS

# Search vector (ADR-034): name, code and barcodes weigh A; brand and tags B; category C. The
# 'simple' configuration (no stemming) suits mixed English/Hindi product names; trigram similarity
# on name and code covers typos.
SEARCH_SQL = """
CREATE FUNCTION catalog_product_search_vector(p catalog_product) RETURNS tsvector
LANGUAGE sql STABLE AS $$
  SELECT
    setweight(to_tsvector('simple', coalesce(p.name, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(p.code, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(
      (SELECT string_agg(b.barcode, ' ') FROM catalog_productbarcode b WHERE b.product_id = p.id),
      '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(
      (SELECT br.name FROM catalog_brand br WHERE br.id = p.brand_id), '')), 'B') ||
    setweight(to_tsvector('simple', coalesce(array_to_string(p.tags, ' '), '')), 'B') ||
    setweight(to_tsvector('simple', coalesce(
      (SELECT c.name FROM catalog_category c WHERE c.id = p.category_id), '')), 'C')
$$;

CREATE FUNCTION catalog_product_search_trigger() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.search_vector := catalog_product_search_vector(NEW);
  RETURN NEW;
END $$;

CREATE TRIGGER catalog_product_search
BEFORE INSERT OR UPDATE ON catalog_product
FOR EACH ROW EXECUTE FUNCTION catalog_product_search_trigger();

-- Barcode, brand and category changes refresh the products they belong to.
CREATE FUNCTION catalog_barcode_touch_product() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  UPDATE catalog_product SET search_vector = NULL
   WHERE id IN (
     SELECT product_id FROM (VALUES (
       CASE WHEN TG_OP = 'DELETE' THEN NULL ELSE NEW.product_id END),
       (CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE OLD.product_id END)) v(product_id)
     WHERE product_id IS NOT NULL);
  RETURN NULL;
END $$;

CREATE TRIGGER catalog_barcode_search
AFTER INSERT OR UPDATE OR DELETE ON catalog_productbarcode
FOR EACH ROW EXECUTE FUNCTION catalog_barcode_touch_product();

CREATE FUNCTION catalog_brand_touch_products() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.name IS DISTINCT FROM OLD.name THEN
    UPDATE catalog_product SET search_vector = NULL WHERE brand_id = NEW.id;
  END IF;
  RETURN NULL;
END $$;

CREATE TRIGGER catalog_brand_search
AFTER UPDATE ON catalog_brand
FOR EACH ROW EXECUTE FUNCTION catalog_brand_touch_products();

CREATE FUNCTION catalog_category_touch_products() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.name IS DISTINCT FROM OLD.name THEN
    UPDATE catalog_product SET search_vector = NULL WHERE category_id = NEW.id;
  END IF;
  RETURN NULL;
END $$;

CREATE TRIGGER catalog_category_search
AFTER UPDATE ON catalog_category
FOR EACH ROW EXECUTE FUNCTION catalog_category_touch_products();
"""

SEARCH_SQL_REVERSE = """
DROP TRIGGER IF EXISTS catalog_category_search ON catalog_category;
DROP FUNCTION IF EXISTS catalog_category_touch_products();
DROP TRIGGER IF EXISTS catalog_brand_search ON catalog_brand;
DROP FUNCTION IF EXISTS catalog_brand_touch_products();
DROP TRIGGER IF EXISTS catalog_barcode_search ON catalog_productbarcode;
DROP FUNCTION IF EXISTS catalog_barcode_touch_product();
DROP TRIGGER IF EXISTS catalog_product_search ON catalog_product;
DROP FUNCTION IF EXISTS catalog_product_search_trigger();
DROP FUNCTION IF EXISTS catalog_product_search_vector(catalog_product);
"""

# Rate history is append-only (PLAN G1b). The only permitted update is cancelling a row once
# (ADR-034); the service allows it only before the row takes effect.
TAX_RATE_SQL = """
CREATE FUNCTION catalog_tax_rate_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'catalog_producttaxrate is append-only' USING ERRCODE = 'integrity_constraint_violation';
  END IF;
  IF OLD.cancelled_at IS NOT NULL OR NEW.cancelled_at IS NULL
     OR (NEW.id, NEW.tenant_id, NEW.product_id, NEW.gst_rate, NEW.cess_type_id, NEW.cess_rate,
         NEW.effective_from, NEW.reason, NEW.created_at)
        IS DISTINCT FROM
        (OLD.id, OLD.tenant_id, OLD.product_id, OLD.gst_rate, OLD.cess_type_id, OLD.cess_rate,
         OLD.effective_from, OLD.reason, OLD.created_at) THEN
    RAISE EXCEPTION 'catalog_producttaxrate rows can only be cancelled' USING ERRCODE = 'integrity_constraint_violation';
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER catalog_tax_rate_guard
BEFORE UPDATE OR DELETE ON catalog_producttaxrate
FOR EACH ROW EXECUTE FUNCTION catalog_tax_rate_guard();
"""

TAX_RATE_SQL_REVERSE = """
DROP TRIGGER IF EXISTS catalog_tax_rate_guard ON catalog_producttaxrate;
DROP FUNCTION IF EXISTS catalog_tax_rate_guard();
"""


def seed_default_units(apps, schema_editor):
    Tenant = apps.get_model("platform", "Tenant")
    Unit = apps.get_model("catalog", "Unit")
    for tenant_id in Tenant.objects.values_list("id", flat=True):
        existing = set(Unit.objects.filter(tenant_id=tenant_id).values_list("code", flat=True))
        Unit.objects.bulk_create(
            [
                Unit(tenant_id=tenant_id, code=code, name=name, allows_decimal=dec, uqc=uqc)
                for code, name, dec, uqc in DEFAULT_UNITS
                if code not in existing
            ]
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform', '0005_settings_overrides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('logo', models.CharField(blank=True, default='', max_length=300)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('sort_order', models.IntegerField(default=0)),
                ('image', models.CharField(blank=True, default='', max_length=300)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('pack_size', common.fields.QtyField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('hsn_code', models.CharField(max_length=8)),
                ('mrp', common.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('base_price', common.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('min_order_qty', common.fields.QtyField(decimal_places=3, default=1, max_digits=14)),
                ('order_multiple', common.fields.QtyField(decimal_places=3, default=1, max_digits=14)),
                ('reorder_level', common.fields.QtyField(decimal_places=3, default=0, max_digits=14)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('show_in_shop', models.BooleanField(default=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_key', models.CharField(max_length=300)),
                ('variants', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.IntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PROCESSING', max_length=12)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductTaxRate',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gst_rate', common.fields.RateField(decimal_places=3, max_digits=6)),
                ('cess_rate', common.fields.RateField(decimal_places=3, default=0, max_digits=6)),
                ('effective_from', models.DateField()),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=200)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cess_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.cesstype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_rates', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=60)),
                ('allows_decimal', models.BooleanField(default=False)),
                ('uqc', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='pack_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.unit'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(models.F('tenant'), django.db.models.functions.text.Lower('name'), condition=models.Q(('deleted_at__isnull', True)), name='uniq_brand_name'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant', 'parent'], name='category_tenant_parent_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 3)), name='category_level_1_to_3'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('parent__isnull', True), ('level', 1)), models.Q(('parent__isnull', False), ('level__gt', 1)), _connector='OR'), name='category_level_matches_parent'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(models.F('tenant'), models.F('parent'), django.db.models.functions.text.Lower('name'), condition=models.Q(('deleted_at__isnull', True)), name='uniq_category_name_per_parent', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='productbarcode',
            constraint=models.UniqueConstraint(fields=('tenant', 'barcode'), name='uniq_barcode'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['tenant', 'product', 'sort_order'], name='product_image_order_idx'),
        ),
        migrations.AddIndex(
            model_name='producttaxrate',
            index=models.Index(fields=['tenant', 'product', '-effective_from'], name='product_rate_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='producttaxrate',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True)), fields=('product', 'effective_from'), name='uniq_product_rate_per_day'),
        ),
        migrations.AddConstraint(
            model_name='producttaxrate',
            constraint=models.CheckConstraint(condition=models.Q(('gst_rate__gte', 0), ('gst_rate__lte', 100)), name='product_rate_range'),
        ),
        migrations.AddConstraint(
            model_name='producttaxrate',
            constraint=models.CheckConstraint(condition=models.Q(('cess_rate__gte', 0), ('cess_rate__lte', 100)), name='product_cess_range'),
        ),
        migrations.AddConstraint(
            model_name='producttaxrate',
            constraint=models.CheckConstraint(condition=models.Q(('cess_type__isnull', False), ('cess_rate', 0), _connector='OR'), name='product_cess_needs_type'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_unit_code'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Upper('code'))), name='unit_code_uppercase'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tenant', 'search_vector'], name='product_search_gin'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='product_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['code'], name='product_code_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'category'], name='product_tenant_category_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'brand'], name='product_tenant_brand_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'is_active', 'name'], name='product_tenant_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(models.F('tenant'), django.db.models.functions.text.Lower('code'), name='uniq_product_code'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('base_price__gte', 0)), name='product_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('mrp__isnull', True), ('mrp__gte', 0), _connector='OR'), name='product_mrp_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('min_order_qty__gt', 0)), name='product_min_qty_pos'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('order_multiple__gt', 0)), name='product_multiple_pos'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('reorder_level__gte', 0)), name='product_reorder_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pack_unit__isnull', True), ('pack_size__isnull', True)), models.Q(('pack_unit__isnull', False), ('pack_size__isnull', False), ('pack_size__gt', 0)), _connector='OR'), name='product_pack_complete'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('hsn_code__regex', '^[0-9]{2,8}$')), name='product_hsn_digits'),
        ),
        EnableRLS("Category"),
        EnableRLS("Brand"),
        EnableRLS("Unit"),
        EnableRLS("Product"),
        EnableRLS("ProductBarcode"),
        EnableRLS("ProductTaxRate"),
        EnableRLS("ProductImage"),
        migrations.RunSQL(SEARCH_SQL, SEARCH_SQL_REVERSE),
        migrations.RunSQL(TAX_RATE_SQL, TAX_RATE_SQL_REVERSE),
        migrations.RunPython(seed_default_units, migrations.RunPython.noop),
    ]
