# Generated by Django 5.2.17 on 2026-09-25 20:54

import common.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_catalog_models'),
        ('platform', '0005_settings_overrides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='own_brand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=common.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__isnull', True), ('cost_price__gte', 0), _connector='OR'), name='product_cost_nonneg'),
        ),
    ]
