# Generated by Django 5.2.17 on 2026-10-02 14:28

import common.search_keys
import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


# The search vector (ADR-034) also holds the name, brand, tags and category in English letters
# (ADR-060 item 8), so "chawal" and "चावल" find each other through full-text prefix matching. The
# trigger runs before the generated name_key is computed, so the vector calls search_key itself.
VECTOR = """
CREATE OR REPLACE FUNCTION catalog_product_search_vector(p catalog_product) RETURNS tsvector
LANGUAGE sql STABLE AS $$
  SELECT
    setweight(to_tsvector('simple', coalesce(p.name, '')), 'A') ||
    setweight(to_tsvector('simple', search_key(coalesce(p.name, ''))), 'A') ||
    setweight(to_tsvector('simple', coalesce(p.code, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(b.codes, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(br.name, '')), 'B') ||
    setweight(to_tsvector('simple', coalesce(array_to_string(p.tags, ' '), '')), 'B') ||
    setweight(to_tsvector('simple',
      search_key(concat_ws(' ', br.name, array_to_string(p.tags, ' ')))), 'B') ||
    setweight(to_tsvector('simple', coalesce(c.name, '')), 'C') ||
    setweight(to_tsvector('simple', search_key(coalesce(c.name, ''))), 'C')
  FROM (SELECT string_agg(barcode, ' ') AS codes
          FROM catalog_productbarcode WHERE product_id = p.id) b
  LEFT JOIN catalog_brand br ON br.id = p.brand_id
  LEFT JOIN catalog_category c ON c.id = p.category_id
$$;
"""

# The vector as created in 0001.
VECTOR_BEFORE = """
CREATE OR REPLACE FUNCTION catalog_product_search_vector(p catalog_product) RETURNS tsvector
LANGUAGE sql STABLE AS $$
  SELECT
    setweight(to_tsvector('simple', coalesce(p.name, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(p.code, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(
      (SELECT string_agg(b.barcode, ' ') FROM catalog_productbarcode b WHERE b.product_id = p.id),
      '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(
      (SELECT br.name FROM catalog_brand br WHERE br.id = p.brand_id), '')), 'B') ||
    setweight(to_tsvector('simple', coalesce(array_to_string(p.tags, ' '), '')), 'B') ||
    setweight(to_tsvector('simple', coalesce(
      (SELECT c.name FROM catalog_category c WHERE c.id = p.category_id), '')), 'C')
$$;
"""

# The trigger refills the vector of every product it touches.
REFRESH = "UPDATE catalog_product SET search_vector = NULL"


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_search_key'),
        ('catalog', '0002_own_brand_cost_price'),
        ('platform', '0008_free_goods_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL([VECTOR, REFRESH], [VECTOR_BEFORE, REFRESH]),
        migrations.AddField(
            model_name='product',
            name='name_key',
            field=models.GeneratedField(db_persist=True, expression=common.search_keys.SearchKey('name'), output_field=models.TextField()),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_key'], name='product_name_key_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
