# Generated by Django 5.2.17 on 2026-09-27 10:55

import common.fields
import common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.db_ops import EnableRLS


def backfill_accounts(apps, schema_editor):
    """Every existing shop gets its account row (the per-shop lock, ADR-044)."""
    Retailer = apps.get_model("retailers", "Retailer")
    RetailerAccount = apps.get_model("ledger", "RetailerAccount")
    RetailerAccount.objects.bulk_create(
        [
            RetailerAccount(tenant_id=tenant_id, retailer_id=pk)
            for pk, tenant_id in Retailer.objects.values_list("pk", "tenant_id")
        ],
        ignore_conflicts=True,
        batch_size=1000,
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform', '0005_settings_overrides'),
        ('retailers', '0006_retailer_price_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerAccount',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', common.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='account', to='retailers.retailer')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        EnableRLS("RetailerAccount"),
        migrations.RunPython(backfill_accounts, migrations.RunPython.noop),
    ]
