# Generated by Django 5.2.17 on 2026-09-28 11:12

import common.fields
import common.ids
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_billing_documents'),
        ('ledger', '0001_retailer_account'),
        ('platform', '0005_settings_overrides'),
        ('retailers', '0006_retailer_price_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', common.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('automatic', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerAdjustment',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('OPENING_DEBIT', 'Opening balance (owed)'), ('OPENING_CREDIT', 'Opening balance (advance)'), ('DEBIT', 'Debit adjustment'), ('CREDIT', 'Credit adjustment')], max_length=14)),
                ('amount', common.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('adjustment_date', models.DateField()),
                ('due_date', models.DateField()),
                ('narration', models.CharField(max_length=300)),
                ('balance_due', common.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('unapplied_amount', common.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('OPENING_BALANCE', 'Opening balance'), ('INVOICE', 'Invoice'), ('CREDIT_NOTE', 'Credit note'), ('PAYMENT', 'Payment'), ('PAYMENT_REVERSAL', 'Payment reversed'), ('DEBIT_ADJUSTMENT', 'Debit adjustment'), ('CREDIT_ADJUSTMENT', 'Credit adjustment')], max_length=17)),
                ('entry_date', models.DateField()),
                ('debit', common.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('credit', common.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('balance_after', common.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('reference_type', models.CharField(max_length=20)),
                ('reference_id', models.UUIDField()),
                ('reference_number', models.CharField(blank=True, default='', max_length=40)),
                ('narration', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='retaileraccount',
            name='last_entry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retaileraccount',
            name='total_credits',
            field=common.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='retaileraccount',
            name='total_debits',
            field=common.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='retaileraccount',
            name='unapplied_credit',
            field=common.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddConstraint(
            model_name='retaileraccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance', django.db.models.expressions.CombinedExpression(models.F('total_debits'), '-', models.F('total_credits')))), name='account_balance_matches_totals'),
        ),
        migrations.AddConstraint(
            model_name='retaileraccount',
            constraint=models.CheckConstraint(condition=models.Q(('unapplied_credit__gte', 0)), name='account_unapplied'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allocation',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='billing.creditnote'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='billing.invoice'),
        ),
    ]
