# Generated by Django 5.2.17 on 2026-09-28 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.db_ops import EnableRLS, MakeAppendOnly


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_ledger_entries'),
        ('payments', '0001_payments'),
        ('platform', '0005_settings_overrides'),
        ('retailers', '0006_retailer_price_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='retailers.retailer'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='reverses',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='ledger.allocation'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant'),
        ),
        migrations.AddField(
            model_name='ledgeradjustment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgeradjustment',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='retailers.retailer'),
        ),
        migrations.AddField(
            model_name='ledgeradjustment',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='credit_adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.ledgeradjustment'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='debit_adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='ledger.ledgeradjustment'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.retaileraccount'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='retailers.retailer'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='reverses',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='ledger.ledgerentry'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant'),
        ),
        migrations.AddIndex(
            model_name='ledgeradjustment',
            index=models.Index(fields=['tenant', 'retailer', 'adjustment_date'], name='adjustment_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgeradjustment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='adjustment_amount_pos'),
        ),
        migrations.AddConstraint(
            model_name='ledgeradjustment',
            constraint=models.CheckConstraint(condition=models.Q(('balance_due__gte', 0), ('balance_due__lte', models.F('amount')), ('unapplied_amount__gte', 0), ('unapplied_amount__lte', models.F('amount'))), name='adjustment_running'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['tenant', 'invoice'], name='allocation_invoice_idx'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['tenant', 'payment'], name='allocation_payment_idx'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['tenant', 'retailer', 'created_at'], name='allocation_retailer_idx'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credit_adjustment__isnull', True), ('credit_note__isnull', True), ('payment__isnull', False)), models.Q(('credit_adjustment__isnull', True), ('credit_note__isnull', False), ('payment__isnull', True)), models.Q(('credit_adjustment__isnull', False), ('credit_note__isnull', True), ('payment__isnull', True)), _connector='OR'), name='allocation_one_source'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit_adjustment__isnull', True), ('invoice__isnull', False)), models.Q(('debit_adjustment__isnull', False), ('invoice__isnull', True)), _connector='OR'), name='allocation_one_target'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__gt', 0), ('reverses__isnull', True)), models.Q(('amount__lt', 0), ('reverses__isnull', False)), _connector='OR'), name='allocation_sign'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['tenant', 'retailer', 'created_at', 'id'], name='ledger_retailer_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['tenant', 'entry_date'], name='ledger_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0), models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR')), name='ledger_one_side'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(fields=('tenant', 'reference_type', 'reference_id', 'entry_type'), name='uniq_ledger_posting'),
        ),
        EnableRLS("LedgerEntry"),
        EnableRLS("LedgerAdjustment"),
        EnableRLS("Allocation"),
        MakeAppendOnly("LedgerEntry"),
        MakeAppendOnly("Allocation"),
    ]
