# Generated by Django 5.2.17 on 2026-09-28 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_allocations'),
        ('platform', '0005_settings_overrides'),
        ('retailers', '0006_retailer_price_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeradjustment',
            name='bill_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='ledgeradjustment',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('adjustment_date'))), name='adjustment_due_after_date'),
        ),
        migrations.AddConstraint(
            model_name='ledgeradjustment',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'OPENING_DEBIT'), models.Q(('bill_number', ''), _negated=True)), fields=('tenant', 'retailer', 'bill_number'), name='uniq_opening_bill'),
        ),
    ]
