# Generated by Django 5.2.17 on 2026-09-28 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_refund_series'),
        ('ledger', '0004_opening_bills'),
        ('payments', '0003_refund'),
        ('platform', '0005_settings_overrides'),
        ('retailers', '0006_retailer_price_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='allocation',
            name='allocation_one_target',
        ),
        migrations.AddField(
            model_name='allocation',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.refund'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('OPENING_BALANCE', 'Opening balance'), ('INVOICE', 'Invoice'), ('CREDIT_NOTE', 'Credit note'), ('PAYMENT', 'Payment'), ('PAYMENT_REVERSAL', 'Payment reversed'), ('DEBIT_ADJUSTMENT', 'Debit adjustment'), ('REFUND', 'Refund paid'), ('CREDIT_ADJUSTMENT', 'Credit adjustment')], max_length=17),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit_adjustment__isnull', True), ('invoice__isnull', False), ('refund__isnull', True)), models.Q(('debit_adjustment__isnull', False), ('invoice__isnull', True), ('refund__isnull', True)), models.Q(('debit_adjustment__isnull', True), ('invoice__isnull', True), ('refund__isnull', False)), _connector='OR'), name='allocation_one_target'),
        ),
    ]
