# Generated by Django 5.2.17 on 2026-09-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_refunds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('OPENING_BALANCE', 'Opening balance'), ('INVOICE', 'Invoice'), ('CREDIT_NOTE', 'Credit note'), ('PAYMENT', 'Payment'), ('PAYMENT_REVERSAL', 'Payment reversed'), ('DEBIT_ADJUSTMENT', 'Debit adjustment'), ('REFUND', 'Refund paid'), ('REFUND_REVERSAL', 'Refund reversed'), ('CREDIT_ADJUSTMENT', 'Credit adjustment')], max_length=17),
        ),
    ]
