# Generated by Django 5.2.17 on 2026-09-25 06:03

import common.ids
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_permissions_and_system_roles'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('platform', '0005_settings_overrides'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoffCode',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('session_expires_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginChallenge',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('STAFF_TENANT_CHOICE', 'Staff: choose a tenant'), ('RETAILER_ACCOUNT_CHOICE', 'Retailer: choose a distributor'), ('MFA', 'Second factor'), ('MFA_ENROLMENT', 'Second factor set-up required')], max_length=30)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=16)),
                ('candidates', models.JSONField(blank=True, default=list)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'हिन्दी'), ('mr', 'मराठी')], default='en', max_length=5),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', True), ('email', django.db.models.functions.text.Lower('email')), _connector='OR'), name='user_email_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('user_type', 'RETAILER'), ('email__isnull', False), _connector='OR'), name='user_staff_and_platform_have_email'),
        ),
        migrations.AddField(
            model_name='handoffcode',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='platform.tenant'),
        ),
        migrations.AddField(
            model_name='handoffcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loginchallenge',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='platform.tenant'),
        ),
        migrations.AddField(
            model_name='loginchallenge',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='handoffcode',
            index=models.Index(fields=['expires_at'], name='handoff_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='loginchallenge',
            index=models.Index(fields=['expires_at'], name='login_challenge_expiry_idx'),
        ),
    ]
