# Generated by Django 5.2.17 on 2026-09-25 06:24

import common.crypto
import common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_login_flow_and_lockout'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginchallenge',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='loginchallenge',
            name='secret',
            field=common.crypto.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_last_step',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=common.crypto.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='loginchallenge',
            name='kind',
            field=models.CharField(choices=[('STAFF_TENANT_CHOICE', 'Staff: choose a tenant'), ('RETAILER_ACCOUNT_CHOICE', 'Retailer: choose a distributor'), ('MFA', 'Second factor'), ('MFA_ENROLMENT', 'Second factor set-up required at sign-in'), ('MFA_SETUP', 'Second factor set-up from account security')], max_length=30),
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_hash', models.CharField(max_length=64)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'code_hash'), name='uniq_recovery_code')],
            },
        ),
    ]
