# Generated by Django 5.2.17 on 2026-09-25 06:35

import common.ids
import django.db.models.deletion
from django.db import migrations, models

from common.db_ops import EnableRLS


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_totp_recovery_codes'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('platform', '0005_settings_overrides'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=16)),
                ('purpose', models.CharField(choices=[('LOGIN', 'Sign in')], default='LOGIN', max_length=10)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], default='SMS', max_length=10)),
                ('code_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('phone__isnull', False), ('tenant__isnull', False), ('user_type', 'RETAILER')), models.Q(models.Q(('user_type', 'RETAILER'), _negated=True), ('tenant__isnull', True)), _connector='OR'), name='user_tenant_only_for_retailers'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('user_type', 'RETAILER')), fields=('tenant', 'phone'), name='uniq_retailer_user_phone_per_tenant'),
        ),
        migrations.AddField(
            model_name='otprequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='platform.tenant'),
        ),
        migrations.AddIndex(
            model_name='otprequest',
            index=models.Index(fields=['phone', '-created_at'], name='otp_phone_created_idx'),
        ),
        migrations.AddIndex(
            model_name='otprequest',
            index=models.Index(fields=['expires_at'], name='otp_expiry_idx'),
        ),
        EnableRLS("OTPRequest", null_tenant_readable=True, null_tenant_insertable=True),
    ]
