# Generated by Django 5.2.17 on 2026-09-25 07:06

import common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.db_ops import EnableRLS


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_invitations'),
        ('platform', '0005_settings_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoffcode',
            name='impersonation_session_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ImpersonationSession',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('mode', models.CharField(choices=[('READ_ONLY', 'Read only'), ('ACT', 'Act')], default='READ_ONLY', max_length=10)),
                ('act_reason', models.TextField(blank=True, default='')),
                ('act_started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('ENDED', 'Ended'), ('EXPIRED', 'Expired')], default='', max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('impersonator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='impersonation_tenant_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('impersonator', models.F('target_user')), _negated=True), name='impersonation_not_self')],
            },
        ),
        EnableRLS("ImpersonationSession"),
    ]
