# Generated by Django 5.2.17 on 2026-10-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_purchasing_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(default='en', max_length=5),
        ),
    ]
