# Generated by Django 5.2.17 on 2026-10-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_languages_from_manifest'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='language',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
