# Generated by Django 5.2.17 on 2026-10-01 05:53

import common.fields
import common.ids
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.db_ops import EnableRLS


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_own_brand_cost_price'),
        ('platform', '0007_purchasing_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_name', models.CharField(blank=True, default='', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=16)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address_line1', models.CharField(blank=True, default='', max_length=200)),
                ('address_line2', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=6)),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=0)),
                ('lead_time_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.state')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('supplier_code', models.CharField(blank=True, default='', max_length=40)),
                ('lead_time_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pack_size', common.fields.QtyField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('last_unit_cost', common.fields.UnitCostField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_links', to='catalog.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='purchasing.supplier')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='supplier_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['tenant', 'name'], name='supplier_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_supplier_code'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('gstin__isnull', False)), fields=('tenant', 'gstin'), name='uniq_supplier_gstin'),
        ),
        migrations.AddIndex(
            model_name='supplierproduct',
            index=models.Index(fields=['tenant', 'product'], name='supplier_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.UniqueConstraint(fields=('supplier', 'product'), name='uniq_supplier_product'),
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('is_preferred', True)), fields=('tenant', 'product'), name='uniq_preferred_supplier'),
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.CheckConstraint(condition=models.Q(('pack_size__isnull', True), ('pack_size__gt', 0), _connector='OR'), name='supplier_pack_positive'),
        ),
        EnableRLS("Supplier"),
        EnableRLS("SupplierProduct"),
    ]
