# Generated by Django 5.2.17 on 2026-10-01 06:09

import common.fields
import common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.db_ops import EnableRLS


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_own_brand_cost_price'),
        ('inventory', '0002_stockinward_supplier'),
        ('platform', '0007_purchasing_flag'),
        ('purchasing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=24)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PARTLY_RECEIVED', 'Partly received'), ('RECEIVED', 'Received'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('supplier_snapshot', models.JSONField(blank=True, default=dict)),
                ('revision', models.PositiveSmallIntegerField(default=0)),
                ('changed_since_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_reason', models.CharField(blank=True, default='', max_length=300)),
                ('subtotal', common.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('estimated_tax', common.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('pdf_key', models.CharField(blank=True, default='', max_length=300)),
                ('plain_pdf_key', models.CharField(blank=True, default='', max_length=300)),
                ('pdf_status', models.CharField(choices=[('PENDING', 'Being prepared'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=8)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='purchasing.supplier')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_no', models.PositiveSmallIntegerField()),
                ('product_code', models.CharField(max_length=40)),
                ('product_name', models.CharField(max_length=200)),
                ('supplier_code', models.CharField(blank=True, default='', max_length=40)),
                ('unit_code', models.CharField(max_length=10)),
                ('entered_unit', models.CharField(choices=[('BASE', 'Base unit'), ('PACK', 'Pack')], default='BASE', max_length=4)),
                ('entered_qty', common.fields.QtyField(decimal_places=3, max_digits=14)),
                ('quantity', common.fields.QtyField(decimal_places=3, max_digits=14)),
                ('unit_cost', common.fields.UnitCostField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('gst_rate', common.fields.RateField(decimal_places=3, default=0, max_digits=6)),
                ('line_total', common.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('qty_received', common.fields.QtyField(decimal_places=3, default=0, max_digits=14)),
                ('qty_cancelled', common.fields.QtyField(decimal_places=3, default=0, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'ordering': ['line_no'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='po_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tenant', 'supplier', 'created_at'], name='po_supplier_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(condition=models.Q(('status__in', ['SENT', 'PARTLY_RECEIVED'])), fields=['tenant', 'expected_date'], name='po_open_expected_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='uniq_po_number'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['tenant', 'product'], name='po_line_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.UniqueConstraint(fields=('order', 'line_no'), name='uniq_po_line_no'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('qty_received__gte', 0), ('qty_cancelled__gte', 0), ('qty_cancelled__lte', models.F('quantity'))), name='po_line_quantities'),
        ),
        EnableRLS("PurchaseOrder"),
        EnableRLS("PurchaseOrderLine"),
    ]
