# Generated by Django 5.2.17 on 2026-09-25 13:17

import common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.db_ops import EnableRLS


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform', '0005_settings_overrides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('PRODUCTS', 'Products'), ('RETAILERS', 'Retailers')], max_length=20)),
                ('mode', models.CharField(choices=[('ADD_ONLY', 'Add new only'), ('ADD_OR_UPDATE', 'Add new and update existing')], max_length=20)),
                ('status', models.CharField(choices=[('VALIDATING', 'Checking the file'), ('VALIDATED', 'Ready to import'), ('FAILED', "Can't be imported"), ('COMMITTING', 'Importing'), ('COMMITTED', 'Imported')], default='VALIDATING', max_length=12)),
                ('file_name', models.CharField(max_length=200)),
                ('file_key', models.CharField(max_length=300)),
                ('report_key', models.CharField(blank=True, default='', max_length=300)),
                ('problem', models.TextField(blank=True, default='')),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('changes', models.JSONField(blank=True, default=list)),
                ('notes', models.JSONField(blank=True, default=list)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('committed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'kind', 'created_at'], name='import_job_idx')],
            },
        ),
        EnableRLS("ImportJob"),
    ]
