# Generated by Django 5.2.17 on 2026-09-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataio', '0001_import_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='kind',
            field=models.CharField(choices=[('PRODUCTS', 'Products'), ('RETAILERS', 'Retailers'), ('SPECIAL_PRICES', 'Special prices'), ('PRICE_LIST_ITEMS', 'Price-list prices'), ('DISCOUNT_RULES', 'Discount rules')], max_length=20),
        ),
    ]
