# Generated by Django 5.2.17 on 2026-09-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataio', '0002_pricing_import_kinds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='kind',
            field=models.CharField(choices=[('PRODUCTS', 'Products'), ('RETAILERS', 'Retailers'), ('SPECIAL_PRICES', 'Special prices'), ('PRICE_LIST_ITEMS', 'Price-list prices'), ('DISCOUNT_RULES', 'Discount rules'), ('OPENING_STOCK', 'Opening stock')], max_length=20),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='mode',
            field=models.CharField(choices=[('ADD_ONLY', 'Add new only'), ('ADD_OR_UPDATE', 'Add new and update existing'), ('STOCK_ADD', 'Add to stock'), ('STOCK_SET', 'Set stock to this count')], max_length=20),
        ),
    ]
