# Generated by Django 5.2.17 on 2026-09-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataio', '0003_opening_stock_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='kind',
            field=models.CharField(choices=[('PRODUCTS', 'Products'), ('RETAILERS', 'Retailers'), ('SPECIAL_PRICES', 'Special prices'), ('PRICE_LIST_ITEMS', 'Price-list prices'), ('DISCOUNT_RULES', 'Discount rules'), ('OPENING_STOCK', 'Opening stock'), ('OPENING_BALANCES', 'Opening balances')], max_length=20),
        ),
    ]
