# Generated by Django 5.2.17 on 2026-09-30 13:59

import common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.db_ops import EnableRLS


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform', '0005_settings_overrides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_code', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('params', models.JSONField(default=dict)),
                ('format', models.CharField(choices=[('XLSX', 'Excel'), ('PDF', 'PDF')], max_length=4)),
                ('status', models.CharField(choices=[('QUEUED', 'Waiting'), ('RUNNING', 'Being made'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='QUEUED', max_length=8)),
                ('own_shops', models.BooleanField(default=False)),
                ('costs', models.BooleanField(default=False)),
                ('file_key', models.CharField(blank=True, default='', max_length=300)),
                ('file_name', models.CharField(blank=True, default='', max_length=150)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, default='', max_length=300)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'requested_by', '-created_at'], name='report_run_mine_idx'), models.Index(fields=['status', 'expires_at'], name='report_run_expiry_idx')],
            },
        ),
        EnableRLS("ReportRun"),
    ]
