# Generated by Django 5.2.17 on 2026-09-28 11:12

import common.fields
import common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.db_ops import EnableRLS


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform', '0005_settings_overrides'),
        ('retailers', '0006_retailer_price_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=16)),
                ('amount', common.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('mode', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('BANK_TRANSFER', 'Bank transfer'), ('UPI', 'UPI')], max_length=13)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PENDING_CLEARANCE', 'Waiting for the cheque to clear'), ('CLEARED', 'Cheque cleared'), ('BOUNCED', 'Cheque bounced'), ('REVERSED', 'Reversed')], max_length=17)),
                ('credit_timing', models.CharField(choices=[('ON_RECEIPT', 'When received'), ('ON_CLEARANCE', 'When cleared')], default='ON_RECEIPT', max_length=12)),
                ('payment_date', models.DateField()),
                ('reference_no', models.CharField(blank=True, default='', max_length=60)),
                ('cheque_number', models.CharField(blank=True, default='', max_length=20)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('handover_status', models.CharField(choices=[('NOT_TRACKED', 'Not tracked'), ('WITH_SALESMAN', 'With salesman'), ('HANDED_OVER', 'Handed over')], default='NOT_TRACKED', max_length=13)),
                ('handed_over_at', models.DateTimeField(blank=True, null=True)),
                ('credited', models.BooleanField(default=False)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('unapplied_amount', common.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.CharField(blank=True, default='', max_length=300)),
                ('receipt_pdf_key', models.CharField(blank=True, default='', max_length=255)),
                ('receipt_pdf_status', models.CharField(default='PENDING', max_length=8)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('handed_over_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='retailers.retailer')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'retailer', 'payment_date'], name='payment_retailer_idx'), models.Index(fields=['tenant', 'status', 'payment_date'], name='payment_status_idx'), models.Index(fields=['tenant', 'handover_status', 'collected_by'], name='payment_handover_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'number'), name='uniq_payment_number'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_pos'), models.CheckConstraint(condition=models.Q(('unapplied_amount__gte', 0), ('unapplied_amount__lte', models.F('amount'))), name='payment_unapplied'), models.CheckConstraint(condition=models.Q(models.Q(('mode', 'CHEQUE'), _negated=True), models.Q(('cheque_number', ''), _negated=True), _connector='OR'), name='payment_cheque_number')],
            },
        ),
        EnableRLS("Payment"),
    ]
