# Generated by Django 5.2.17 on 2026-09-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='handover_status',
            field=models.CharField(choices=[('NOT_TRACKED', 'Not tracked'), ('WITH_SALESMAN', 'With salesman'), ('HANDED_OVER', 'Handed over'), ('NOT_NEEDED', 'Nothing to hand over')], default='NOT_TRACKED', max_length=13),
        ),
    ]
