# Generated by Django 5.2.17 on 2026-09-28 13:38

import common.fields
import common.ids
import django.db.models.deletion
from django.conf import settings
from common.db_ops import EnableRLS
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_handover_status'),
        ('platform', '0005_settings_overrides'),
        ('retailers', '0006_retailer_price_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=16)),
                ('amount', common.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank transfer'), ('UPI', 'UPI')], max_length=13)),
                ('refund_date', models.DateField()),
                ('reference_no', models.CharField(blank=True, default='', max_length=60)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('balance_due', common.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('voucher_pdf_key', models.CharField(blank=True, default='', max_length=255)),
                ('voucher_pdf_status', models.CharField(default='PENDING', max_length=8)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='retailers.retailer')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'retailer', 'refund_date'], name='refund_retailer_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'number'), name='uniq_refund_number'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_pos'), models.CheckConstraint(condition=models.Q(('balance_due__gte', 0), ('balance_due__lte', models.F('amount'))), name='refund_balance')],
            },
        ),
        EnableRLS("Refund"),
    ]
