# Generated by Django 5.2.17 on 2026-09-29 19:22

import common.crypto
import common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.db_ops import EnableRLS


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_refund_reversal'),
        ('platform', '0005_settings_overrides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('BANK_TRANSFER', 'Bank transfer'), ('UPI', 'UPI'), ('ONLINE', 'Paid online')], max_length=13),
        ),
        migrations.CreateModel(
            name='GatewayConfig',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('MOCK', 'Test gateway (development)')], max_length=10)),
                ('mode', models.CharField(choices=[('TEST', 'Test'), ('LIVE', 'Live')], default='TEST', max_length=4)),
                ('key_id', common.crypto.EncryptedTextField(default='')),
                ('key_secret', common.crypto.EncryptedTextField(default='')),
                ('webhook_secret', common.crypto.EncryptedTextField(default='')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('UNVERIFIED', 'Not checked'), ('CHECKING', 'Checking'), ('VERIFIED', 'Working'), ('FAILED', 'Not working')], default='UNVERIFIED', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=300)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='uniq_gateway_config')],
            },
        ),
        EnableRLS("GatewayConfig"),
    ]
