# Generated by Django 5.2.17 on 2026-09-29 20:16

import common.fields
import common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.db_ops import EnableRLS


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_reissued_invoices'),
        ('payments', '0005_gateway_config'),
        ('platform', '0005_settings_overrides'),
        ('retailers', '0008_retaileraddress_distance_km'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=10)),
                ('event_id', models.CharField(max_length=80)),
                ('kind', models.CharField(max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('result', models.CharField(blank=True, default='', max_length=40)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_payment_id',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_provider',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='review_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('INVOICE', 'A bill'), ('OUTSTANDING', 'Everything owed'), ('CUSTOM', "An amount of the shop's choice")], max_length=11)),
                ('amount', common.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('provider', models.CharField(max_length=10)),
                ('provider_order_id', models.CharField(blank=True, default='', max_length=60)),
                ('status', models.CharField(choices=[('CREATED', 'Ready to pay'), ('ATTEMPTED', 'Tried'), ('PAID', 'Paid'), ('EXPIRED', 'Expired')], default='CREATED', max_length=9)),
                ('checkout', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
                ('client_outcome', models.CharField(blank=True, default='', max_length=10)),
                ('last_error', models.CharField(blank=True, default='', max_length=300)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.invoice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payments.payment')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='retailers.retailer')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='intent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentintent'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_payment_id', ''), _negated=True), fields=('tenant', 'gateway_provider', 'gateway_payment_id'), name='uniq_gateway_payment'),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='intent_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['CREATED', 'ATTEMPTED'])), fields=('tenant', 'retailer', 'purpose', 'invoice'), name='uniq_active_checkout', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_order_id', ''), _negated=True), fields=('provider', 'provider_order_id'), name='uniq_gateway_order'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='intent_amount_pos'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('invoice__isnull', False), ('purpose', 'INVOICE')), models.Q(models.Q(('purpose', 'INVOICE'), _negated=True), ('invoice__isnull', True)), _connector='OR'), name='intent_invoice_for_bills'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('tenant', 'provider', 'event_id'), name='uniq_webhook_event'),
        ),
        EnableRLS("PaymentIntent"),
        EnableRLS("WebhookEvent"),
    ]
