# Generated by Django 5.2.17 on 2026-10-03 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.ids
from common.db_ops import EnableRLS


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0008_document_language"),
        ("platform", "0010_sms_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckoutBrowserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code_hash", models.CharField(max_length=64, unique=True)),
                ("code_expires_at", models.DateTimeField()),
                ("session_hash", models.CharField(blank=True, default="", max_length=64)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="payments.paymentintent",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant", "intent"], name="pay_session_intent_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("session_hash", ""), _negated=True),
                        fields=("session_hash",),
                        name="uniq_pay_session",
                    )
                ],
            },
        ),
        EnableRLS("CheckoutBrowserSession"),
    ]
