# Generated by Django 5.2.17 on 2026-10-01 05:40

import common.fields
import common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.db_ops import EnableRLS


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_own_brand_cost_price'),
        ('platform', '0005_settings_overrides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStats',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('computed_at', models.DateTimeField()),
                ('demand_days', models.PositiveSmallIntegerField()),
                ('demand_qty', common.fields.QtyField(decimal_places=3, default=0, max_digits=14)),
                ('per_day', common.fields.QtyField(decimal_places=3, default=0, max_digits=14)),
                ('movement_days', models.PositiveSmallIntegerField()),
                ('sold_value', common.fields.MoneyField(decimal_places=2, default=0, max_digits=14)),
                ('abc_class', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, null=True)),
                ('movement_class', models.CharField(blank=True, choices=[('FAST', 'Fast'), ('SLOW', 'Slow'), ('DEAD', 'Dead'), ('NEW', 'New')], max_length=4, null=True)),
                ('last_sale_date', models.DateField(blank=True, null=True)),
                ('available', common.fields.QtyField(decimal_places=3, default=0, max_digits=14)),
                ('days_of_stock', models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'verbose_name_plural': 'product stats',
                'indexes': [models.Index(condition=models.Q(('abc_class__isnull', False)), fields=['tenant', 'abc_class'], name='stats_abc_idx'), models.Index(condition=models.Q(('movement_class__isnull', False)), fields=['tenant', 'movement_class'], name='stats_movement_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('demand_qty__gte', 0), ('per_day__gte', 0)), name='stats_demand_positive')],
            },
        ),
        EnableRLS("ProductStats"),
    ]
