# Generated by Django 5.2.17 on 2026-10-01 06:42

import common.fields
import common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.db_ops import EnableRLS


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_own_brand_cost_price'),
        ('planning', '0001_initial'),
        ('platform', '0007_purchasing_flag'),
        ('purchasing', '0002_purchase_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReorderSuggestion',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ORDERED', 'Ordered'), ('DISMISSED', 'Dismissed'), ('RESOLVED', 'No longer needed')], default='OPEN', max_length=9)),
                ('computed_at', models.DateTimeField()),
                ('basis', models.CharField(choices=[('DEMAND', 'Daily demand'), ('LOW_HISTORY', 'Little or no sales history')], max_length=11)),
                ('demand_qty', common.fields.QtyField(decimal_places=3, default=0, max_digits=14)),
                ('demand_days', models.PositiveSmallIntegerField()),
                ('per_day', common.fields.QtyField(decimal_places=3, default=0, max_digits=14)),
                ('available', common.fields.QtyField(decimal_places=3, default=0, max_digits=14)),
                ('on_order', common.fields.QtyField(decimal_places=3, default=0, max_digits=14)),
                ('waiting', common.fields.QtyField(decimal_places=3, default=0, max_digits=14)),
                ('reorder_level', common.fields.QtyField(decimal_places=3, default=0, max_digits=14)),
                ('lead_days', models.PositiveSmallIntegerField()),
                ('lead_source', models.CharField(choices=[('PRODUCT_SUPPLIER', "The supplier's time for this product"), ('SUPPLIER', "The supplier's usual time"), ('DEFAULT', 'Your usual delivery time')], max_length=16)),
                ('safety_days', models.PositiveSmallIntegerField()),
                ('cover_days', models.PositiveSmallIntegerField()),
                ('reorder_point', common.fields.QtyField(decimal_places=3, default=0, max_digits=14)),
                ('pack_size', common.fields.QtyField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('suggested_qty', common.fields.QtyField(decimal_places=3, max_digits=14)),
                ('quantity', common.fields.QtyField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('days_left', models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_until', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_suggestions', to='catalog.product')),
                ('purchase_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='purchasing.purchaseorderline')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='purchasing.supplier')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status'], name='suggestion_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('tenant', 'product'), name='uniq_open_suggestion'), models.CheckConstraint(condition=models.Q(('suggested_qty__gt', 0), models.Q(('quantity__isnull', True), ('quantity__gt', 0), _connector='OR')), name='suggestion_quantities')],
            },
        ),
        EnableRLS("ReorderSuggestion"),
    ]
