# Generated by Django 5.2.17 on 2026-10-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_reorder_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='reordersuggestion',
            name='last_sale_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reordersuggestion',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ORDERED', 'Ordered'), ('DISMISSED', 'Dismissed'), ('RESOLVED', 'No longer needed'), ('NOT_SELLING', 'Below its reorder level, not selling')], default='OPEN', max_length=11),
        ),
    ]
