# Generated by Django 5.2.17 on 2026-09-29 17:40

import common.crypto
import common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.db_ops import EnableRLS


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0003_refund_series'),
        ('platform', '0005_settings_overrides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EInvoiceRecord',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('CREDIT_NOTE', 'Credit note')], max_length=11)),
                ('document_number', models.CharField(max_length=16)),
                ('document_number_key', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Waiting to be sent'), ('SUBMITTED', 'Sent, waiting for the portal'), ('GENERATED', 'IRN generated'), ('FAILED', 'IRN failed'), ('CANCELLED', 'IRN cancelled')], default='PENDING', max_length=9)),
                ('irn', models.CharField(blank=True, default='', max_length=64)),
                ('ack_no', models.CharField(blank=True, default='', max_length=20)),
                ('ack_date', models.DateTimeField(blank=True, null=True)),
                ('signed_invoice', models.TextField(blank=True, default='')),
                ('signed_qr', models.TextField(blank=True, default='')),
                ('request_document', models.JSONField(default=dict)),
                ('response', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=30)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('retryable', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason_code', models.CharField(blank=True, default='', max_length=20)),
                ('cancel_remarks', models.CharField(blank=True, default='', max_length=100)),
                ('cancel_outcome', models.CharField(blank=True, choices=[('REISSUE', 'Re-issued with a new number'), ('TAKE_BACK', 'Goods taken back')], default='', max_length=9)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('credit_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.creditnote')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.invoice')),
                ('reissued_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.invoice')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status'], name='einvoice_status_idx'), models.Index(fields=['tenant', 'document_number_key'], name='einvoice_number_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('credit_note__isnull', True), ('document_type', 'INVOICE'), ('invoice__isnull', False)), models.Q(('credit_note__isnull', False), ('document_type', 'CREDIT_NOTE'), ('invoice__isnull', True)), _connector='OR'), name='einvoice_one_document'), models.UniqueConstraint(condition=models.Q(('invoice__isnull', False)), fields=('invoice',), name='uniq_einvoice_invoice'), models.UniqueConstraint(condition=models.Q(('credit_note__isnull', False)), fields=('credit_note',), name='uniq_einvoice_credit_note')],
            },
        ),
        migrations.CreateModel(
            name='GstCredential',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=30)),
                ('environment', models.CharField(choices=[('SANDBOX', 'Sandbox'), ('PRODUCTION', 'Production')], default='SANDBOX', max_length=10)),
                ('gstin', models.CharField(max_length=15)),
                ('credentials', common.crypto.EncryptedTextField(default='')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('UNVERIFIED', 'Not checked'), ('CHECKING', 'Checking'), ('VERIFIED', 'Working'), ('FAILED', 'Not working')], default='UNVERIFIED', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=300)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'provider'), name='uniq_gst_credential')],
            },
        ),
        EnableRLS("GstCredential"),
        EnableRLS("EInvoiceRecord"),
    ]
