# Generated by Django 5.2.17 on 2026-09-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_compliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='einvoicerecord',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
