# Generated by Django 5.2.17 on 2026-09-29 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_einvoice_requested'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='einvoicerecord',
            name='cancel_error',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='einvoicerecord',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='einvoicerecord',
            name='cancel_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='einvoicerecord',
            name='cancel_to_backorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='einvoicerecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Waiting to be sent'), ('SUBMITTED', 'Sent, waiting for the portal'), ('GENERATED', 'IRN generated'), ('FAILED', 'IRN failed'), ('CANCELLING', 'Cancelling'), ('CANCELLED', 'IRN cancelled')], default='PENDING', max_length=10),
        ),
    ]
