# Generated by Django 5.2.17 on 2026-09-29 19:01

import common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.db_ops import EnableRLS


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_reissued_invoices'),
        ('compliance', '0003_irn_cancellation'),
        ('orders', '0008_fulfilment_distance_km'),
        ('platform', '0005_settings_overrides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EWayBill',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Waiting to be sent'), ('SUBMITTED', 'Sent, waiting for the portal'), ('GENERATED', 'Generated'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=9)),
                ('consignment_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ewb_number', models.CharField(blank=True, default='', max_length=20)),
                ('ewb_date', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('transport_mode', models.CharField(choices=[('ROAD', 'Road'), ('RAIL', 'Rail'), ('AIR', 'Air'), ('SHIP', 'Ship')], default='ROAD', max_length=4)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=20)),
                ('transporter_id', models.CharField(blank=True, default='', max_length=15)),
                ('transporter_name', models.CharField(blank=True, default='', max_length=120)),
                ('transport_doc_no', models.CharField(blank=True, default='', max_length=40)),
                ('transport_doc_date', models.DateField(blank=True, null=True)),
                ('distance_km', models.PositiveIntegerField(blank=True, null=True)),
                ('request_document', models.JSONField(default=dict)),
                ('response', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=30)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('retryable', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fulfilment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orders.fulfilment')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.invoice')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='EWayBillUpdate',
            fields=[
                ('id', models.UUIDField(default=common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('PART_B', 'Vehicle updated'), ('CANCEL', 'Cancelled')], max_length=6)),
                ('status', models.CharField(choices=[('PENDING', 'Waiting to be sent'), ('DONE', 'Done'), ('FAILED', 'Refused')], default='PENDING', max_length=7)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=20)),
                ('transport_doc_no', models.CharField(blank=True, default='', max_length=40)),
                ('reason_code', models.CharField(max_length=30)),
                ('remarks', models.CharField(blank=True, default='', max_length=100)),
                ('request_document', models.JSONField(default=dict)),
                ('response', models.JSONField(default=dict)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('eway_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='compliance.ewaybill')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='ewaybill',
            index=models.Index(fields=['tenant', 'status'], name='ewaybill_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='ewaybill',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['CANCELLED', 'FAILED']), _negated=True), fields=('invoice',), name='uniq_live_ewaybill_per_invoice'),
        ),
        migrations.AddIndex(
            model_name='ewaybillupdate',
            index=models.Index(fields=['tenant', 'status'], name='ewaybill_update_status_idx'),
        ),
        EnableRLS("EWayBill"),
        EnableRLS("EWayBillUpdate"),
    ]
