# Generated by Django 5.2.17 on 2026-10-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_ewaybills'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewaybillupdate',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
